/**
	Generates haxe.c's simple lowercase mapping from the pinned Haxe Eval target.

	The generated header is the runtime's only mapping table. Keeping generation
	beside a byte-exact check prevents hand-maintained C ranges from drifting from
	the source-language observer. Eval currently maps each Unicode scalar to at
	most one scalar; generation stops if that contract changes.
**/
final class GenerateLowercaseData {
	static final OUTPUT_PATH = "runtime/hxrt/include/hxrt/string_lower_case_data.h";
	static final MAXIMUM_SCALAR = 0x10FFFF;

	/** Return true for scalar values that UTF-8 can represent directly. **/
	static function isUnicodeScalar(value:Int):Bool
		return value < 0xD800 || value > 0xDFFF;

	/** Render the complete deterministic C mapping table. **/
	static function render():String {
		final output = new StringBuf();
		output.add("/*\n");
		output.add(" * Generated by test/differential/string-runtime/GenerateLowercaseData.hx.\n");
		output.add(" * Run `haxe -cp test/differential/string-runtime --run GenerateLowercaseData --check` to verify.\n");
		output.add(" *\n");
		output.add(" * hxrt feature: string-lower-case generated mapping data.\n");
		output.add(" * This is Haxe Eval's locale-independent, one-scalar lowercase table.\n");
		output.add(" * Do not edit mappings by hand.\n");
		output.add(" */\n");
		output.add("#ifndef HXRT_STRING_LOWER_CASE_DATA_H_INCLUDED\n");
		output.add("#define HXRT_STRING_LOWER_CASE_DATA_H_INCLUDED\n\n");
		output.add("static const uint32_t hxc_lower_case_mappings[][2] = {\n");
		var mappingCount = 0;
		for (scalar in 0...MAXIMUM_SCALAR + 1) {
			if (!isUnicodeScalar(scalar))
				continue;
			final source = String.fromCharCode(scalar);
			final lowered = source.toLowerCase();
			if (lowered.length != 1)
				throw 'Eval lowercase mapping for U+${StringTools.hex(scalar, 6)} produced ${lowered.length} scalars';
			final result = lowered.charCodeAt(0);
			if (result == null)
				throw 'Eval lowercase mapping for U+${StringTools.hex(scalar, 6)} produced no scalar';
			if (result != scalar) {
				output.add("  { UINT32_C(0x");
				output.add(StringTools.hex(scalar, 6));
				output.add("), UINT32_C(0x");
				output.add(StringTools.hex(result, 6));
				output.add(") },\n");
				mappingCount += 1;
			}
		}
		output.add("};\n\n");
		output.add("#define HXC_LOWER_CASE_MAPPING_COUNT ((size_t)");
		output.add(Std.string(mappingCount));
		output.add("u)\n\n");
		output.add("#endif /* HXRT_STRING_LOWER_CASE_DATA_H_INCLUDED */\n");
		return output.toString();
	}

	/** Write or verify the generated table according to one explicit mode. **/
	static function main():Void {
		final arguments = Sys.args();
		if (arguments.length != 1 || (arguments[0] != "--check" && arguments[0] != "--write")) {
			Sys.println("usage: GenerateLowercaseData --check|--write");
			Sys.exit(2);
		}
		final expected = render();
		if (arguments[0] == "--write") {
			sys.io.File.saveContent(OUTPUT_PATH, expected);
			Sys.println('lowercase-data: wrote $OUTPUT_PATH');
			return;
		}
		if (!sys.FileSystem.exists(OUTPUT_PATH) || sys.io.File.getContent(OUTPUT_PATH) != expected) {
			Sys.println('lowercase-data: ERROR: $OUTPUT_PATH differs from pinned Eval');
			Sys.exit(1);
		}
		Sys.println('lowercase-data: OK: $OUTPUT_PATH matches pinned Eval');
	}
}
