#include "hxc/program.h"

#include <stdint.h>

int main(void);

int main(void)
{
  enum HXC_MODE_TAG mode = HXC_MODE_ON;
  struct HXC_OPTION_INT_TAG some = {
    .HXC_OPTION_INT_TAG_MEMBER = HXC_OPTION_INT_SOME,
    .HXC_OPTION_INT_PAYLOAD_MEMBER.HXC_OPTION_INT_SOME_UNION
      .HXC_OPTION_INT_SOME_VALUE = INT32_C(7),
  };
  struct HXC_OPTION_BOOL_TAG truth = {
    .HXC_OPTION_BOOL_TAG_MEMBER = HXC_OPTION_BOOL_SOME,
    .HXC_OPTION_BOOL_PAYLOAD_MEMBER.HXC_OPTION_BOOL_SOME_UNION
      .HXC_OPTION_BOOL_SOME_VALUE = true,
  };
  struct HXC_CHAIN_TAG tail = {
    .HXC_CHAIN_TAG_MEMBER = HXC_CHAIN_END,
    .HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_END_UNION.HXC_CHAIN_END_VALUE =
      INT32_C(2),
  };
  struct HXC_CHAIN_TAG head = {
    .HXC_CHAIN_TAG_MEMBER = HXC_CHAIN_LINK,
    .HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_LINK_UNION.HXC_CHAIN_LINK_VALUE =
      INT32_C(1),
    .HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_LINK_UNION.HXC_CHAIN_LINK_NEXT =
      &tail,
  };

  return mode == HXC_MODE_ON &&
      some.HXC_OPTION_INT_TAG_MEMBER == HXC_OPTION_INT_SOME &&
      some.HXC_OPTION_INT_PAYLOAD_MEMBER.HXC_OPTION_INT_SOME_UNION
        .HXC_OPTION_INT_SOME_VALUE == INT32_C(7) &&
      truth.HXC_OPTION_BOOL_PAYLOAD_MEMBER.HXC_OPTION_BOOL_SOME_UNION
        .HXC_OPTION_BOOL_SOME_VALUE &&
      head.HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_LINK_UNION
        .HXC_CHAIN_LINK_NEXT == &tail &&
      head.HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_LINK_UNION
        .HXC_CHAIN_LINK_NEXT->HXC_CHAIN_PAYLOAD_MEMBER.HXC_CHAIN_END_UNION
        .HXC_CHAIN_END_VALUE == INT32_C(2)
    ? 0
    : 1;
}
