package caxecraft.content;

/**
 * Supplies reviewed visual names to the runtime content-schema boundary.
 *
 * The complete asset manifest is larger than the bounded package JSON parser
 * and owns byte provenance beyond this child task. This inventory therefore
 * carries only the manifest ID and exact cells referenced by the current base
 * content pack. The parent publication step must bind these facts to the
 * reviewed manifest hash before replacing generated packaging glue.
 */
final class RuntimeAssetInventory {
	/** Reviewed SHA-256 of the complete asset-manifest source bytes. */
	public static inline final REVIEWED_MANIFEST_SHA256 = "70d322eb2908ddb908121f8952f6de27d95203d51a46ffa56adecf7efb1abd25";

	final manifestIdValue:String;
	final assets:Array<RuntimeAssetFacts>;

	/** Construct one immutable inventory from independently reviewed facts. */
	private function new(manifestId:String, assets:Array<RuntimeAssetFacts>) {
		this.manifestIdValue = manifestId;
		this.assets = assets;
	}

	/**
	 * Return the exact visual subset referenced by the shipped base pack.
	 *
	 * Expected values are manually transcribed from `assets/manifest.json`, not
	 * generated by the runtime decoder under test. Publication still has to
	 * prove that the source manifest hash and this reviewed subset agree.
	 */
	public static function reviewedBase():RuntimeAssetInventory {
		return new RuntimeAssetInventory("caxecraft-showcase-v1-draft", [
			new RuntimeAssetFacts("adventure-items", [
				"tideweave-suit-folded",
				"tideweave-helmet",
				"tideweave-air-canister",
				"tideweave-suit-pickup",
				"bounds-ward",
				"inlining-spark",
				"zero-cost-charm",
				"cleanup-crest",
				"glyph-wave",
				"glyph-leaf",
				"glyph-ember",
				"glyph-forge",
				"bridge-input",
				"bridge-routing-elbow",
				"checkpoint",
				"ceesh-scroll"
			]),
			new RuntimeAssetFacts("entities", [
				"moss-front",
				"moss-three-quarter",
				"moss-side",
				"moss-back",
				"nia-front",
				"nia-three-quarter",
				"nia-side",
				"nia-back",
				"mossling-front",
				"mossling-three-quarter",
				"mossling-side",
				"mossling-back",
				"ember-wisp-front",
				"ember-wisp-three-quarter",
				"ember-wisp-side",
				"ember-wisp-back"
			]),
			new RuntimeAssetFacts("items", [
				"grass-block",
				"soil-block",
				"slate-stone",
				"oak-log",
				"wood-pick",
				"stone-axe",
				"stone-shovel",
				"copper-sword",
				"amber-shard",
				"copper-nugget",
				"berries",
				"bread",
				"map",
				"lantern",
				"healing-herbs",
				"quest-token"
			]),
			new RuntimeAssetFacts("terrain", [
				"meadow-grass-top",
				"grass-side",
				"rich-soil",
				"slate-stone",
				"river-sand",
				"teal-water",
				"bark-side",
				"log-top",
				"leafy-canopy",
				"oak-planks",
				"field-cobble",
				"clay-brick",
				"charcoal-ore",
				"copper-ore",
				"amber-crystal-ore",
				"foundation-rock"
			])
		]);
	}

	/** Exact manifest pack ID these facts were reviewed against. */
	public inline function manifestId():String
		return manifestIdValue;

	/** True when the reviewed subset contains one asset ID. */
	public function hasAsset(id:String):Bool {
		for (asset in assets)
			if (asset.id == id)
				return true;
		return false;
	}

	/** Return the exact cell index, or -1 when the asset/cell pair is absent. */
	public function cellIndex(assetId:String, cellId:String):Int {
		for (asset in assets)
			if (asset.id == assetId)
				for (index in 0...asset.cells.length)
					if (asset.cells[index] == cellId)
						return index;
		return -1;
	}
}

/** One reviewed visual asset and its ordered semantic cell names. */
final class RuntimeAssetFacts {
	/** Stable asset ID used by content presentation records. */
	public final id:String;

	/** Manifest-ordered cell IDs; the array never escapes this module. */
	public final cells:Array<String>;

	/** Construct one immutable asset fact set from checked manifest prose. */
	public function new(id:String, cells:Array<String>) {
		this.id = id;
		this.cells = cells;
	}
}
