#ifndef HXC_RAYLIB_SMOKE_CONSTANTS_H_INCLUDED
#define HXC_RAYLIB_SMOKE_CONSTANTS_H_INCLUDED

#include <stdint.h>

#define HXC_RAYLIB_SMOKE_SIZE INT32_C(16)
#define HXC_RAYLIB_SMOKE_CENTER INT32_C(8)
#define HXC_RAYLIB_SMOKE_COLOR UINT32_C(0x102030ff)

#endif /* HXC_RAYLIB_SMOKE_CONSTANTS_H_INCLUDED */
