#ifndef HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED
#define HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

struct hxc_type_compiler_haxezx2Dclass_RootRecord;

struct hxc_type_compiler_haxezx2Dclass_MiddleRecord;

struct hxc_type_compiler_haxezx2Dclass_LeafRecord;

struct hxc_type_compiler_haxezx2Dclass_EmptyBase;

struct hxc_type_compiler_haxezx2Dclass_EmptyLeaf;

struct hxc_type_compiler_haxezx2Dclass_RootRecord {
  int32_t hxc_field_compiler_haxezx2Dclass_RootRecord_field_rootValue_n0;
};

struct hxc_type_compiler_haxezx2Dclass_MiddleRecord {
  struct hxc_type_compiler_haxezx2Dclass_RootRecord hxc_field_compiler_haxezx2Dclass_MiddleRecord_base_n0;
  bool hxc_field_compiler_haxezx2Dclass_MiddleRecord_field_enabled_n1;
};

struct hxc_type_compiler_haxezx2Dclass_LeafRecord {
  struct hxc_type_compiler_haxezx2Dclass_MiddleRecord hxc_field_compiler_haxezx2Dclass_LeafRecord_base_n0;
  double hxc_field_compiler_haxezx2Dclass_LeafRecord_field_score_n1;
  struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_field_compiler_haxezx2Dclass_LeafRecord_field_peer_n2;
};

struct hxc_type_compiler_haxezx2Dclass_EmptyBase {
  unsigned char hxc_field_compiler_haxezx2Dclass_EmptyBase_emptyzx2Danchor_n0;
};

struct hxc_type_compiler_haxezx2Dclass_EmptyLeaf {
  struct hxc_type_compiler_haxezx2Dclass_EmptyBase hxc_field_compiler_haxezx2Dclass_EmptyLeaf_base_n0;
};

struct hxc_type_compiler_haxezx2Dclass_EmptyBase *hxc_method_ClassLayoutFixture_asEmptyBase(struct hxc_type_compiler_haxezx2Dclass_EmptyLeaf *hxc_local_ClassLayoutFixture_asEmptyBase_value_n0);

struct hxc_type_compiler_haxezx2Dclass_MiddleRecord *hxc_method_ClassLayoutFixture_asMiddle(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_asMiddle_value_n0);

struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_method_ClassLayoutFixture_asRoot(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_asRoot_value_n0);

bool hxc_method_ClassLayoutFixture_different(struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_different_left_n0, struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_different_right_n1);

bool hxc_method_ClassLayoutFixture_isNull(struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_isNull_value_n0);

void hxc_method_ClassLayoutFixture_main(void);

int32_t hxc_method_ClassLayoutFixture_readInherited(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_readInherited_value_n0);

struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_method_ClassLayoutFixture_readPeer(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_readPeer_value_n0);

int32_t hxc_method_ClassLayoutFixture_readRoot(struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_readRoot_value_n0);

double hxc_method_ClassLayoutFixture_readScore(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_readScore_value_n0);

bool hxc_method_ClassLayoutFixture_same(struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_same_left_n0, struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_same_right_n1);

int32_t hxc_method_ClassLayoutFixture_writeInherited(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_writeInherited_value_n0, int32_t hxc_local_ClassLayoutFixture_writeInherited_next_n1);

struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_method_ClassLayoutFixture_writePeer(struct hxc_type_compiler_haxezx2Dclass_LeafRecord *hxc_local_ClassLayoutFixture_writePeer_value_n0, struct hxc_type_compiler_haxezx2Dclass_RootRecord *hxc_local_ClassLayoutFixture_writePeer_peer_n1);

#endif /* HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED */
