package raylib.raw;

/**
 * ABI-faithful raylib 6.0 struct `BoundingBox` from raylib.h:457.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Struct)
@:c.include("raylib.h", c.IncludeKind.System)
extern class BoundingBox {
	public var min:Vector3;

	public var max:Vector3;
}
