package raylib.raw;

/**
 * ABI-faithful raylib 6.0 struct `Camera3D` from raylib.h:325.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Struct)
@:c.include("raylib.h", c.IncludeKind.System)
extern class Camera3D {
	public var position:Vector3;

	public var target:Vector3;

	public var up:Vector3;

	public var fovy:c.Float32;

	public var projection:c.Int32;
}
