package raylib.raw;

/**
 * ABI-faithful raylib 6.0 closed enum `CameraProjection` from raylib.h:952.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Enum)
@:c.include("raylib.h", c.IncludeKind.System)
extern enum CameraProjection {
	CAMERA_PERSPECTIVE;

	CAMERA_ORTHOGRAPHIC;
}
