package raylib.raw;

/**
 * ABI-faithful raylib 6.0 closed enum `ConfigFlags` from raylib.h:553.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Enum)
@:c.include("raylib.h", c.IncludeKind.System)
extern enum ConfigFlags {
	FLAG_VSYNC_HINT;

	FLAG_FULLSCREEN_MODE;

	FLAG_WINDOW_RESIZABLE;

	FLAG_WINDOW_UNDECORATED;

	FLAG_WINDOW_HIDDEN;

	FLAG_WINDOW_MINIMIZED;

	FLAG_WINDOW_MAXIMIZED;

	FLAG_WINDOW_UNFOCUSED;

	FLAG_WINDOW_TOPMOST;

	FLAG_WINDOW_ALWAYS_RUN;

	FLAG_WINDOW_TRANSPARENT;

	FLAG_WINDOW_HIGHDPI;

	FLAG_WINDOW_MOUSE_PASSTHROUGH;

	FLAG_BORDERLESS_WINDOWED_MODE;

	FLAG_MSAA_4X_HINT;

	FLAG_INTERLACED_HINT;
}
