package raylib.raw;

/**
 * ABI-faithful raylib 6.0 closed enum `GamepadAxis` from raylib.h:758.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Enum)
@:c.include("raylib.h", c.IncludeKind.System)
extern enum GamepadAxis {
	GAMEPAD_AXIS_LEFT_X;

	GAMEPAD_AXIS_LEFT_Y;

	GAMEPAD_AXIS_RIGHT_X;

	GAMEPAD_AXIS_RIGHT_Y;

	GAMEPAD_AXIS_LEFT_TRIGGER;

	GAMEPAD_AXIS_RIGHT_TRIGGER;
}
