package raylib.raw;

/**
 * ABI-faithful raylib 6.0 closed enum `GamepadButton` from raylib.h:736.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Enum)
@:c.include("raylib.h", c.IncludeKind.System)
extern enum GamepadButton {
	GAMEPAD_BUTTON_UNKNOWN;

	GAMEPAD_BUTTON_LEFT_FACE_UP;

	GAMEPAD_BUTTON_LEFT_FACE_RIGHT;

	GAMEPAD_BUTTON_LEFT_FACE_DOWN;

	GAMEPAD_BUTTON_LEFT_FACE_LEFT;

	GAMEPAD_BUTTON_RIGHT_FACE_UP;

	GAMEPAD_BUTTON_RIGHT_FACE_RIGHT;

	GAMEPAD_BUTTON_RIGHT_FACE_DOWN;

	GAMEPAD_BUTTON_RIGHT_FACE_LEFT;

	GAMEPAD_BUTTON_LEFT_TRIGGER_1;

	GAMEPAD_BUTTON_LEFT_TRIGGER_2;

	GAMEPAD_BUTTON_RIGHT_TRIGGER_1;

	GAMEPAD_BUTTON_RIGHT_TRIGGER_2;

	GAMEPAD_BUTTON_MIDDLE_LEFT;

	GAMEPAD_BUTTON_MIDDLE;

	GAMEPAD_BUTTON_MIDDLE_RIGHT;

	GAMEPAD_BUTTON_LEFT_THUMB;

	GAMEPAD_BUTTON_RIGHT_THUMB;
}
