package raylib.raw;

/**
 * ABI-faithful raylib 6.0 struct `Model` from raylib.h:416.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Struct)
@:c.include("raylib.h", c.IncludeKind.System)
/** The included header owns this value's complete field layout. */
extern class Model {}
