package raylib.raw;

/**
 * ABI-faithful raylib 6.0 closed enum `MouseButton` from raylib.h:710.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Enum)
@:c.include("raylib.h", c.IncludeKind.System)
extern enum MouseButton {
	MOUSE_BUTTON_LEFT;

	MOUSE_BUTTON_RIGHT;

	MOUSE_BUTTON_MIDDLE;

	MOUSE_BUTTON_SIDE;

	MOUSE_BUTTON_EXTRA;

	MOUSE_BUTTON_FORWARD;

	MOUSE_BUTTON_BACK;
}
