package raylib.raw;

/**
 * ABI-faithful raylib 6.0 struct `RayCollision` from raylib.h:449.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.layout(c.Layout.Struct)
@:c.include("raylib.h", c.IncludeKind.System)
extern class RayCollision {
	public var hit:Bool;

	public var distance:c.Float32;

	public var point:Vector3;

	public var normal:Vector3;
}
