package raylib.raw;

/**
 * ABI-faithful raylib 6.0 function namespace `Raylib` from raylib.h:986.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
#if raylib_system_pkg_config
@:c.pkgConfig("raylib")
#elseif raylib_platform_linux
@:c.link("raylib")
@:c.link("m")
	#if raylib_configuration_desktop
	@:c.link("pthread") @:c.link("GL") @:c.link("X11") @:c.link("dl") @:c.link("rt")
	#end
#elseif raylib_platform_macos
@:c.link("raylib")
	#if raylib_configuration_desktop
	@:c.framework("OpenGL") @:c.framework("Cocoa") @:c.framework("IOKit") @:c.framework("CoreFoundation")
	#end
#elseif raylib_platform_windows
@:c.link("raylib")
@:c.link("winmm")
	#if raylib_configuration_desktop
	@:c.link("opengl32") @:c.link("gdi32") @:c.link("shell32") @:c.link("user32")
	#end
#end
@:c.include("raylib.h", c.IncludeKind.System)
extern class Raylib {
	public static function BeginDrawing():Void;

	public static function BeginMode3D(camera:Camera3D):Void;

	public static function CheckCollisionBoxes(box1:BoundingBox, box2:BoundingBox):Bool;

	public static function ClearBackground(color:Color):Void;

	public static function CloseWindow():Void;

	public static function DisableCursor():Void;

	public static function DrawCircle(centerX:c.Int32, centerY:c.Int32, radius:c.Float32, color:Color):Void;

	public static function DrawCube(position:Vector3, width:c.Float32, height:c.Float32, length:c.Float32, color:Color):Void;

	public static function DrawCubeV(position:Vector3, size:Vector3, color:Color):Void;

	public static function DrawCubeWires(position:Vector3, width:c.Float32, height:c.Float32, length:c.Float32, color:Color):Void;

	public static function DrawCubeWiresV(position:Vector3, size:Vector3, color:Color):Void;

	public static function DrawFPS(posX:c.Int32, posY:c.Int32):Void;

	public static function DrawGrid(slices:c.Int32, spacing:c.Float32):Void;

	public static function DrawLine(startPosX:c.Int32, startPosY:c.Int32, endPosX:c.Int32, endPosY:c.Int32, color:Color):Void;

	public static function DrawLine3D(startPos:Vector3, endPos:Vector3, color:Color):Void;

	public static function DrawPixel(posX:c.Int32, posY:c.Int32, color:Color):Void;

	public static function DrawRectangle(posX:c.Int32, posY:c.Int32, width:c.Int32, height:c.Int32, color:Color):Void;

	public static function DrawRectangleLines(posX:c.Int32, posY:c.Int32, width:c.Int32, height:c.Int32, color:Color):Void;

	public static function DrawSphere(centerPos:Vector3, radius:c.Float32, color:Color):Void;

	public static function DrawSphereWires(centerPos:Vector3, radius:c.Float32, rings:c.Int32, slices:c.Int32, color:Color):Void;

	public static function DrawText(text:c.CString, posX:c.Int32, posY:c.Int32, fontSize:c.Int32, color:Color):Void;

	public static function EnableCursor():Void;

	public static function EndDrawing():Void;

	public static function EndMode3D():Void;

	public static function GetColor(hexValue:c.UInt32):Color;

	public static function GetFPS():c.Int32;

	public static function GetFrameTime():c.Float32;

	public static function GetMouseDelta():Vector2;

	public static function GetMousePosition():Vector2;

	public static function GetMouseWheelMove():c.Float32;

	public static function GetRayCollisionBox(ray:Ray, box:BoundingBox):RayCollision;

	public static function GetRayCollisionSphere(ray:Ray, center:Vector3, radius:c.Float32):RayCollision;

	public static function GetScreenHeight():c.Int32;

	public static function GetScreenToWorldRay(position:Vector2, camera:Camera):Ray;

	public static function GetScreenWidth():c.Int32;

	public static function GetTime():Float;

	public static function InitWindow(width:c.Int32, height:c.Int32, title:c.CString):Void;

	public static function IsCursorHidden():Bool;

	public static function IsKeyDown(key:c.Int32):Bool;

	public static function IsKeyPressed(key:c.Int32):Bool;

	public static function IsKeyReleased(key:c.Int32):Bool;

	public static function IsMouseButtonDown(button:c.Int32):Bool;

	public static function IsMouseButtonPressed(button:c.Int32):Bool;

	public static function IsMouseButtonReleased(button:c.Int32):Bool;

	public static function IsWindowFocused():Bool;

	public static function IsWindowReady():Bool;

	public static function IsWindowResized():Bool;

	public static function SetConfigFlags(flags:c.UInt32):Void;

	public static function SetExitKey(key:c.Int32):Void;

	public static function SetTargetFPS(fps:c.Int32):Void;

	public static function SetTraceLogLevel(logLevel:c.Int32):Void;

	public static function SetWindowMinSize(width:c.Int32, height:c.Int32):Void;

	public static function SetWindowSize(width:c.Int32, height:c.Int32):Void;

	public static function WindowShouldClose():Bool;
}
