package raylib.raw;

/**
 * ABI-faithful raylib 6.0 rlgl quad-batch namespace from rlgl.h:618.
 *
 * Generated by scripts/raylib/rlgl_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
#if raylib_system_pkg_config
@:c.pkgConfig("raylib")
#elseif raylib_platform_linux
@:c.link("raylib")
@:c.link("m")
	#if raylib_configuration_desktop
	@:c.link("pthread") @:c.link("GL") @:c.link("X11") @:c.link("dl") @:c.link("rt")
	#end
#elseif raylib_platform_macos
@:c.link("raylib")
	#if raylib_configuration_desktop
	@:c.framework("OpenGL") @:c.framework("Cocoa") @:c.framework("IOKit") @:c.framework("CoreFoundation")
	#end
#elseif raylib_platform_windows
@:c.link("raylib")
@:c.link("winmm")
	#if raylib_configuration_desktop
	@:c.link("opengl32") @:c.link("gdi32") @:c.link("shell32") @:c.link("user32")
	#end
#end
@:c.include("rlgl.h", c.IncludeKind.System)
extern class Rlgl {
	public static function rlBegin(mode:c.Int32):Void;

	public static function rlColor4ub(r:c.UInt8, g:c.UInt8, b:c.UInt8, a:c.UInt8):Void;

	public static function rlDrawRenderBatchActive():Void;

	public static function rlEnd():Void;

	public static function rlNormal3f(x:c.Float32, y:c.Float32, z:c.Float32):Void;

	public static function rlSetTexture(id:c.UInt32):Void;

	public static function rlTexCoord2f(x:c.Float32, y:c.Float32):Void;

	public static function rlVertex3f(x:c.Float32, y:c.Float32, z:c.Float32):Void;
}
