package raylib.raw;

/**
 * ABI-faithful raylib 6.0 typedef alias `Texture2D` from raylib.h:280.
 *
 * Generated by scripts/raylib/core_binding.py from commit dbc56a87da87d973a9c5baa4e7438a9d20121d28.
 * Edit the selection/generator and run the registered snapshot updater;
 * do not hand-edit this raw declaration.
 */
@:c.include("raylib.h", c.IncludeKind.System)
typedef Texture2D = Texture;
