#ifndef HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED
#define HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits(uint32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0 <= UINT32_C(2147483647))
  {
    return (int32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0;
  }
  return INT32_MIN + (int32_t)(hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0 - UINT32_C(2147483648));
}

static inline double hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0, double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1 != 0.0)
  {
    return hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 / hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 == 0.0 || hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 != hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0)
  {
    return NAN;
  }
  return signbit(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0) != signbit(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1) ? -INFINITY : INFINITY;
}

static inline double hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Emodulo(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_left_n0, double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1 == 0.0)
  {
    return NAN;
  }
  return fmod(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_left_n0, hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1);
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 != hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0)
  {
    return 0;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 >= 2147483647.0)
  {
    return INT32_MAX;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 <= -2147483648.0)
  {
    return INT32_MIN;
  }
  return (int32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0;
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_left_n0 + (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_left_n0 & (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dnot(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dnot_value_n0)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)~(uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dnot_value_n0);
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dor(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_left_n0 | (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dxor(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_left_n0 ^ (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1 == 0 || (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0 == INT32_MIN && hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1 == -1))
  {
    return 0;
  }
  return hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0 % hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1;
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_left_n0 * (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_left_n0 << ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_right_n1 & (uint32_t)31)));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits(((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 & UINT32_C(2147483648)) == 0 ? (uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)) : (uint32_t)~(uint64_t)(uint32_t)((uint64_t)(uint32_t)~(uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Esubtractzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_left_n0 - (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)));
}

int32_t hxc_method_PrimitiveDifferentialFixture_faddInt(double hxc_local_PrimitiveDifferentialFixture_faddInt_left_n0, double hxc_local_PrimitiveDifferentialFixture_faddInt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_fdivInt(double hxc_local_PrimitiveDifferentialFixture_fdivInt_left_n0, double hxc_local_PrimitiveDifferentialFixture_fdivInt_right_n1);

bool hxc_method_PrimitiveDifferentialFixture_feq(double hxc_local_PrimitiveDifferentialFixture_feq_left_n0, double hxc_local_PrimitiveDifferentialFixture_feq_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_fint(double hxc_local_PrimitiveDifferentialFixture_fint_value_n0);

bool hxc_method_PrimitiveDifferentialFixture_flt(double hxc_local_PrimitiveDifferentialFixture_flt_left_n0, double hxc_local_PrimitiveDifferentialFixture_flt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_fmodInt(double hxc_local_PrimitiveDifferentialFixture_fmodInt_left_n0, double hxc_local_PrimitiveDifferentialFixture_fmodInt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_fmulInt(double hxc_local_PrimitiveDifferentialFixture_fmulInt_left_n0, double hxc_local_PrimitiveDifferentialFixture_fmulInt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_fsubInt(double hxc_local_PrimitiveDifferentialFixture_fsubInt_left_n0, double hxc_local_PrimitiveDifferentialFixture_fsubInt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_iadd(int32_t hxc_local_PrimitiveDifferentialFixture_iadd_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_iadd_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_iand(int32_t hxc_local_PrimitiveDifferentialFixture_iand_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_iand_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_idivInt(int32_t hxc_local_PrimitiveDifferentialFixture_idivInt_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_idivInt_right_n1);

bool hxc_method_PrimitiveDifferentialFixture_ieq(int32_t hxc_local_PrimitiveDifferentialFixture_ieq_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ieq_right_n1);

bool hxc_method_PrimitiveDifferentialFixture_ilt(int32_t hxc_local_PrimitiveDifferentialFixture_ilt_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ilt_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_imod(int32_t hxc_local_PrimitiveDifferentialFixture_imod_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_imod_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_imul(int32_t hxc_local_PrimitiveDifferentialFixture_imul_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_imul_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_inot(int32_t hxc_local_PrimitiveDifferentialFixture_inot_value_n0);

int32_t hxc_method_PrimitiveDifferentialFixture_ior(int32_t hxc_local_PrimitiveDifferentialFixture_ior_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ior_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_ishl(int32_t hxc_local_PrimitiveDifferentialFixture_ishl_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ishl_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_ishr(int32_t hxc_local_PrimitiveDifferentialFixture_ishr_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ishr_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_isub(int32_t hxc_local_PrimitiveDifferentialFixture_isub_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_isub_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_iushr(int32_t hxc_local_PrimitiveDifferentialFixture_iushr_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_iushr_right_n1);

int32_t hxc_method_PrimitiveDifferentialFixture_ixor(int32_t hxc_local_PrimitiveDifferentialFixture_ixor_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ixor_right_n1);

void hxc_method_PrimitiveDifferentialFixture_main(void);

uint32_t hxc_method_PrimitiveDifferentialFixture_uadd(uint32_t hxc_local_PrimitiveDifferentialFixture_uadd_left_n0, uint32_t hxc_local_PrimitiveDifferentialFixture_uadd_right_n1);

bool hxc_method_PrimitiveDifferentialFixture_ult(uint32_t hxc_local_PrimitiveDifferentialFixture_ult_left_n0, uint32_t hxc_local_PrimitiveDifferentialFixture_ult_right_n1);

uint32_t hxc_method_PrimitiveDifferentialFixture_umod(uint32_t hxc_local_PrimitiveDifferentialFixture_umod_left_n0, uint32_t hxc_local_PrimitiveDifferentialFixture_umod_right_n1);

uint32_t hxc_method_PrimitiveDifferentialFixture_umul(uint32_t hxc_local_PrimitiveDifferentialFixture_umul_left_n0, uint32_t hxc_local_PrimitiveDifferentialFixture_umul_right_n1);

uint32_t hxc_method_PrimitiveDifferentialFixture_ushl(uint32_t hxc_local_PrimitiveDifferentialFixture_ushl_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ushl_right_n1);

uint32_t hxc_method_PrimitiveDifferentialFixture_ushr(uint32_t hxc_local_PrimitiveDifferentialFixture_ushr_left_n0, int32_t hxc_local_PrimitiveDifferentialFixture_ushr_right_n1);

uint32_t hxc_method_PrimitiveDifferentialFixture_usub(uint32_t hxc_local_PrimitiveDifferentialFixture_usub_left_n0, uint32_t hxc_local_PrimitiveDifferentialFixture_usub_right_n1);

#endif /* HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED */
