package reflaxe.c.emit;

import reflaxe.c.emit.CBuildPlan.CBuildArtifactKind;
import reflaxe.c.emit.CBuildPlan.CBuildPlanBuilder;
import reflaxe.c.emit.CBuildPlan.CBuildPlanSnapshot;
import reflaxe.c.emit.CBuildPlan.CBuildStandard;
import reflaxe.c.emit.CBuildPlan.CBuildWarningPolicy;
import reflaxe.c.emit.GeneratedFile.GeneratedFileKind;

/** Pure optional CMake/Meson views over one validated neutral build plan. */
class CBuildAdapterEmitter {
	public static inline final CMAKE_PATH = "cmake/CMakeLists.txt";
	public static inline final MESON_PATH = "meson.build";

	public function new() {}

	public function emit(projectName:String, plan:CBuildPlanSnapshot):Array<GeneratedFile> {
		validate(plan);
		return [
			new GeneratedFile(CMAKE_PATH, renderCMake(projectName, plan), GeneratedFileKind.CMakeAdapter),
			new GeneratedFile(MESON_PATH, renderMeson(projectName, plan), GeneratedFileKind.MesonAdapter)
		];
	}

	function renderCMake(projectName:String, plan:CBuildPlanSnapshot):String {
		final output = new StringBuf();
		line(output, "# Generated by reflaxe.c from hxc.manifest.json build schema 1.");
		line(output, "# Optional adapter: the JSON manifest remains the build-system-neutral authority.");
		line(output, "cmake_minimum_required(VERSION 3.21)");
		line(output, 'project(${cmakeLiteral(projectName)} LANGUAGES C)');
		line(output);
		line(output, 'add_executable(${plan.artifact.targetName}');
		for (source in plan.sources) {
			line(output, '  ${cmakeLiteral("../" + source)}');
		}
		line(output, ")");
		line(output);
		line(output, 'set_target_properties(${plan.artifact.targetName} PROPERTIES');
		line(output, "  C_EXTENSIONS OFF");
		line(output, '  C_STANDARD ${cmakeStandard(plan.cStandard)}');
		line(output, "  C_STANDARD_REQUIRED YES");
		line(output, "  RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/bin\"");
		line(output, ")");
		line(output);
		line(output, 'if(CMAKE_C_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$")');
		line(output, '  target_compile_options(${plan.artifact.targetName} PRIVATE');
		for (flag in strictCFlags()) {
			line(output, '    ${cmakeLiteral(flag)}');
		}
		line(output, "  )");
		line(output, "endif()");
		if (plan.includeDirectories.length > 0) {
			line(output);
			line(output, 'target_include_directories(${plan.artifact.targetName} PRIVATE');
			for (directory in plan.includeDirectories) {
				line(output, '  ${cmakeLiteral("../" + directory)}');
			}
			line(output, ")");
		}
		if (plan.definitions.length > 0) {
			line(output);
			line(output, 'target_compile_definitions(${plan.artifact.targetName} PRIVATE');
			for (definition in plan.definitions) {
				line(output, '  ${cmakeLiteral(definition.name + "=" + definition.compilerValue)}');
			}
			line(output, ")");
		}
		if (plan.pkgConfigPackages.length > 0) {
			line(output);
			line(output, "find_package(PkgConfig REQUIRED)");
			for (index in 0...plan.pkgConfigPackages.length) {
				final variable = numbered("HXC_PKG", index);
				line(output, 'pkg_check_modules($variable REQUIRED IMPORTED_TARGET ${cmakeLiteral(plan.pkgConfigPackages[index].name)})');
				line(output, 'target_link_libraries(${plan.artifact.targetName} PRIVATE PkgConfig::$variable)');
			}
		}
		if (plan.frameworks.length > 0) {
			line(output);
			line(output, "if(NOT APPLE)");
			line(output, '  message(FATAL_ERROR ${cmakeLiteral("the neutral build plan requires Apple frameworks")})');
			line(output, "endif()");
			for (index in 0...plan.frameworks.length) {
				final variable = numbered("HXC_FRAMEWORK", index);
				line(output, 'find_library($variable NAMES ${cmakeLiteral(plan.frameworks[index].name)} REQUIRED)');
				line(output, "target_link_libraries(" + plan.artifact.targetName + " PRIVATE \"${" + variable + "}\")");
			}
		}
		if (plan.libraries.length > 0) {
			line(output);
			line(output, 'target_link_libraries(${plan.artifact.targetName} PRIVATE');
			for (library in plan.libraries) {
				line(output, '  ${cmakeLiteral(library.name)}');
			}
			line(output, ")");
		}
		return output.toString();
	}

	function renderMeson(projectName:String, plan:CBuildPlanSnapshot):String {
		final output = new StringBuf();
		line(output, "# Generated by reflaxe.c from hxc.manifest.json build schema 1.");
		line(output, "# Optional adapter: the JSON manifest remains the build-system-neutral authority.");
		line(output, 'project(${mesonLiteral(projectName)}, ${mesonLiteral("c")},');
		line(output, '  meson_version: ${mesonLiteral(">=1.4.0")},');
		line(output, "  default_options: [");
		line(output, '    ${mesonLiteral("c_std=" + mesonStandard(plan.cStandard))},');
		line(output, '    ${mesonLiteral("warning_level=3")},');
		line(output, '    ${mesonLiteral("werror=true")},');
		line(output, "  ],");
		line(output, ")");
		line(output);
		line(output, "hxc_cc = meson.get_compiler('c')");
		line(output, "hxc_sources = files(");
		for (source in plan.sources) {
			line(output, '  ${mesonLiteral(source)},');
		}
		line(output, ")");
		line(output, "hxc_include_directories = [");
		for (directory in plan.includeDirectories) {
			line(output, '  include_directories(${mesonLiteral(directory)}),');
		}
		line(output, "]");
		line(output, "hxc_c_args = [");
		for (definition in plan.definitions) {
			line(output, '  ${mesonLiteral("-D" + definition.name + "=" + definition.compilerValue)},');
		}
		line(output, "]");
		line(output, "hxc_dependencies = [");
		for (library in plan.libraries) {
			line(output, '  hxc_cc.find_library(${mesonLiteral(library.name)}, required: true),');
		}
		for (pkg in plan.pkgConfigPackages) {
			line(output, '  dependency(${mesonLiteral(pkg.name)}, required: true),');
		}
		for (framework in plan.frameworks) {
			line(output, '  dependency(${mesonLiteral("appleframeworks")}, modules: [${mesonLiteral(framework.name)}], required: true),');
		}
		line(output, "]");
		line(output);
		line(output, 'executable(${mesonLiteral(plan.artifact.targetName)}, hxc_sources,');
		line(output, "  include_directories: hxc_include_directories,");
		line(output, "  c_args: hxc_c_args,");
		line(output, "  dependencies: hxc_dependencies,");
		line(output, "  install: false,");
		line(output, ")");
		return output.toString();
	}

	static function validate(plan:CBuildPlanSnapshot):Void {
		if (plan.schemaVersion != CBuildPlanBuilder.SCHEMA_VERSION
			|| plan.artifact.kind != CBuildArtifactKind.Executable
			|| plan.artifact.targetName != CBuildPlanBuilder.EXECUTABLE_TARGET
			|| plan.extensions
			|| plan.warningPolicy != CBuildWarningPolicy.Strict
			|| plan.sources.length == 0) {
			throw new ProjectEmissionError("build adapters require the validated executable-only strict schema-1 neutral plan");
		}
	}

	static function cmakeStandard(standard:CBuildStandard):String {
		return switch standard {
			case C11: "11";
			case C17: "17";
			case C23Experimental: "23";
			case _: throw new ProjectEmissionError('cannot render unknown CMake C standard `${Std.string(standard)}`');
		};
	}

	static function mesonStandard(standard:CBuildStandard):String {
		return switch standard {
			case C11: "c11";
			case C17: "c17";
			case C23Experimental: "c23";
			case _: throw new ProjectEmissionError('cannot render unknown Meson C standard `${Std.string(standard)}`');
		};
	}

	static function strictCFlags():Array<String>
		return [
			"-Wall",
			"-Wextra",
			"-Werror",
			"-pedantic",
			"-Wshadow",
			"-Wconversion",
			"-Wsign-conversion",
			"-Wstrict-prototypes",
			"-Wmissing-prototypes",
			"-Wundef",
			"-Wformat=2",
			"-Wimplicit-fallthrough",
			"-Wcast-align",
			"-Wcast-qual"
		];

	/** CMake bracket arguments perform no substitution or escape processing. */
	static function cmakeLiteral(value:String):String {
		var equals = "";
		while (value.indexOf("]" + equals + "]") != -1) {
			equals += "=";
		}
		return "[" + equals + "[" + value + "]" + equals + "]";
	}

	static function mesonLiteral(value:String):String {
		final escapedBackslashes = StringTools.replace(value, "\\", "\\\\");
		return "'" + StringTools.replace(escapedBackslashes, "'", "\\'") + "'";
	}

	static function numbered(prefix:String, index:Int):String {
		if (index < 0 || index > 999) {
			throw new ProjectEmissionError('build adapter cannot address `$prefix` ordinal `$index`');
		}
		return prefix + "_" + StringTools.lpad(Std.string(index), "0", 3);
	}

	static function line(output:StringBuf, ?value:String):Void {
		if (value != null) {
			output.add(value);
		}
		output.add("\n");
	}
}
