package reflaxe.c.emit;

import haxe.io.Bytes;
#if (macro || reflaxe_runtime)
import reflaxe.c.CPhaseTiming;
import reflaxe.c.CPhaseTiming.CProfileCounterId;
#end
import reflaxe.c.emit.CContentDigest.sha256Hex;
import reflaxe.c.emit.GeneratedFile.GeneratedFileKind;

/**
	Owns the compiler server's one-generation cache of generated-file digests.

	Hashing a generated C project is useful but expensive: SHA-256 must inspect
	every UTF-8 byte even when an edit leaves most files unchanged. This module
	keeps only the previous successful request's immutable path, role, complete
	text, byte length, and digest. A later request reuses the address only after
	all three identity fields and the full text compare exactly.

	The cache deliberately does not retain typed Haxe values, compiler contexts,
	IR, output managers, or partially written projects. `beginRequest` creates a
	fresh request-local lookup; `completeRequest` publishes a replacement
	generation only after Reflaxe reports that output completed; and
	`abortRequest` discards request state without touching the prior generation.
**/
/** The immutable content address returned to `GeneratedFile`. */
typedef GeneratedFileContentAddress = {
	final sha256:String;
	final byteLength:Int;
}

/** Bounded evidence reported after one cache request completes. */
typedef GeneratedFileDigestCacheStats = {
	final enabled:Bool;
	final hits:Int;
	final misses:Int;
	final retainedEntries:Int;
	final retainedBytes:Float;
}

private typedef PersistedGeneratedFileDigest = {
	final relativePath:String;
	final contents:String;
	final kind:GeneratedFileKind;
	final sha256:String;
	final byteLength:Int;
}

private typedef GeneratedFileDigestCacheRequest = {
	final enabled:Bool;
	final priorByPath:Map<String, PersistedGeneratedFileDigest>;
	var hits:Int;
	var misses:Int;
}

/**
	Reuses only content addresses whose complete immutable inputs are identical.

	This is a stateful class rather than a group of module-level functions
	because it owns a process lifetime: one successful compiler-server request
	may supply evidence to the next request. The mutable lookup and counters are
	still recreated for every compilation. See `docs/architecture.md` for the
	broader rule that semantic compiler state must remain request-local.
**/
@:noCompletion
class GeneratedFileDigestCache {
	/**
		Disables warm digest reuse without changing generated bytes.

		This define is a cold-path verification control. It lets differential tests
		prove that cache hits are only an optimization and never an alternate source
		of generated output.
	**/
	public static inline final DISABLE_DEFINE = "reflaxe_c_test_disable_generated_digest_cache";

	#if (eval && macro)
	@:persistent
	#end
	static var previousGeneration:Array<PersistedGeneratedFileDigest> = [];

	static var activeRequest:Null<GeneratedFileDigestCacheRequest> = null;

	/**
		Start one fresh request and index the prior complete generation.

		Calling this after a failed request intentionally replaces only its
		uncommitted lookup and counters. The persistent successful generation is
		left unchanged until `completeRequest`.
	**/
	public static function beginRequest(enabled:Bool):Void {
		final priorByPath:Map<String, PersistedGeneratedFileDigest> = [];
		if (enabled) {
			for (entry in previousGeneration)
				priorByPath.set(entry.relativePath, entry);
		}
		activeRequest = {
			enabled: enabled,
			priorByPath: priorByPath,
			hits: 0,
			misses: 0
		};
	}

	/**
		Content-address one validated generated artifact.

		A hit still compares the entire immutable Haxe string. That linear
		comparison is cheaper than converting the string to a second UTF-8 byte
		buffer and running SHA-256, while making hash collisions and incomplete
		keys irrelevant: unequal text always takes the normal hashing path.

		Direct structural tools that construct `GeneratedFile` outside the main
		compiler lifecycle have no active request, so they use the authoritative
		uncached implementation.
	**/
	public static function address(relativePath:String, contents:String, kind:GeneratedFileKind):GeneratedFileContentAddress {
		final request = activeRequest;
		if (request != null && request.enabled) {
			final prior = request.priorByPath.get(relativePath);
			if (prior != null && prior.kind == kind && prior.contents == contents) {
				request.hits++;
				return {
					sha256: prior.sha256,
					byteLength: prior.byteLength
				};
			}
		}

		final encoded = Bytes.ofString(contents);
		if (request != null)
			request.misses++;
		return {
			sha256: sha256Hex(encoded),
			byteLength: encoded.length
		};
	}

	/**
		Publish the final artifact set after the whole output transaction succeeds.

		`files` must be the exact array accepted by the output writer. Building
		the persistent generation here, rather than while constructors run,
		excludes temporary planning values and ensures the retained set is
		bounded to one completed project's artifacts.
	**/
	public static function completeRequest(files:Array<GeneratedFile>):GeneratedFileDigestCacheStats {
		final request = activeRequest;
		if (request == null)
			throw new haxe.Exception("generated-file digest cache completed without an active request");

		if (request.enabled) {
			final replacement:Array<PersistedGeneratedFileDigest> = [];
			for (file in files) {
				replacement.push({
					relativePath: file.relativePath,
					contents: file.contents,
					kind: file.kind,
					sha256: file.contentSha256,
					byteLength: file.contentByteLength
				});
			}
			previousGeneration = replacement;
		}

		var retainedBytes = 0.0;
		for (entry in previousGeneration)
			retainedBytes += entry.byteLength;
		final stats:GeneratedFileDigestCacheStats = {
			enabled: request.enabled,
			hits: request.hits,
			misses: request.misses,
			retainedEntries: previousGeneration.length,
			retainedBytes: retainedBytes
		};
		activeRequest = null;
		#if (macro || reflaxe_runtime)
		CPhaseTiming.setCounter(CPCounterGeneratedDigestCacheHits, stats.hits);
		CPhaseTiming.setCounter(CPCounterGeneratedDigestCacheMisses, stats.misses);
		CPhaseTiming.setCounter(CPCounterGeneratedDigestCacheRetainedEntries, stats.retainedEntries);
		CPhaseTiming.setCounterFloat(CPCounterGeneratedDigestCacheRetainedBytes, stats.retainedBytes);
		#end
		return stats;
	}

	/**
		Discard the current request while preserving its last successful predecessor.

		This is safe to call when no request is active, which keeps error paths
		simple and prevents cleanup code from masking the original diagnostic.
	**/
	public static function abortRequest():Void
		activeRequest = null;
}
