#ifndef HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED
#define HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits(uint32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0 <= UINT32_C(2147483647))
  {
    return (int32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0;
  }
  return INT32_MIN + (int32_t)(hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Etozx2Ei32zx2Ebits_value_n0 - UINT32_C(2147483648));
}

static inline double hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0, double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1 != 0.0)
  {
    return hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 / hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 == 0.0 || hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0 != hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0)
  {
    return NAN;
  }
  return signbit(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_left_n0) != signbit(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe_right_n1) ? -INFINITY : INFINITY;
}

static inline double hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Emodulo(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_left_n0, double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1 == 0.0)
  {
    return NAN;
  }
  return fmod(hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_left_n0, hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Emodulo_right_n1);
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(double hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 != hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0)
  {
    return 0;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 >= 2147483647.0)
  {
    return INT32_MAX;
  }
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0 <= -2147483648.0)
  {
    return INT32_MIN;
  }
  return (int32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating_value_n0;
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_left_n0 + (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eaddzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_left_n0 & (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dand_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dnot(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dnot_value_n0)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)~(uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dnot_value_n0);
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dor(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_left_n0 | (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dor_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dxor(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_left_n0 ^ (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Ebitzx2Dxor_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1 == 0 || (hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0 == INT32_MIN && hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1 == -1))
  {
    return 0;
  }
  return hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_left_n0 % hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emodulozx2Ezzerozx2Dsafe_right_n1;
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_left_n0 * (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Emultiplyzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Enegatezx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Enegatezx2Ewrapping_value_n0)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)0 - (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Enegatezx2Ewrapping_value_n0));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_left_n0 << ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Dleftzx2Emasked_right_n1 & (uint32_t)31)));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits(((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 & UINT32_C(2147483648)) == 0 ? (uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)) : (uint32_t)~(uint64_t)(uint32_t)((uint64_t)(uint32_t)~(uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Esubtractzx2Ewrapping(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_left_n0 - (uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Esubtractzx2Ewrapping_right_n1));
}

static inline int32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked(int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_left_n0, int32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_right_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Etozx2Ei32zx2Ebits((uint32_t)((uint64_t)(uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_left_n0 >> ((uint32_t)hxc_local_compiler_primitivezx2Dhelper_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked_right_n1 & (uint32_t)31)));
}

static inline uint32_t hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe(uint32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe_left_n0, uint32_t hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe_right_n1)
{
  if (hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe_right_n1 == 0)
  {
    return 0;
  }
  return hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe_left_n0 % hxc_local_compiler_primitivezx2Dhelper_hxczx2Eu32zx2Emodulozx2Ezzerozx2Dsafe_right_n1;
}

double hxc_method_ArithmeticFixture_fadd(double hxc_local_ArithmeticFixture_fadd_left_n0, double hxc_local_ArithmeticFixture_fadd_right_n1);

double hxc_method_ArithmeticFixture_fdiv(double hxc_local_ArithmeticFixture_fdiv_left_n0, double hxc_local_ArithmeticFixture_fdiv_right_n1);

bool hxc_method_ArithmeticFixture_fequal(double hxc_local_ArithmeticFixture_fequal_left_n0, double hxc_local_ArithmeticFixture_fequal_right_n1);

int32_t hxc_method_ArithmeticFixture_fint(double hxc_local_ArithmeticFixture_fint_value_n0);

double hxc_method_ArithmeticFixture_fmod(double hxc_local_ArithmeticFixture_fmod_left_n0, double hxc_local_ArithmeticFixture_fmod_right_n1);

double hxc_method_ArithmeticFixture_fmul(double hxc_local_ArithmeticFixture_fmul_left_n0, double hxc_local_ArithmeticFixture_fmul_right_n1);

double hxc_method_ArithmeticFixture_fneg(double hxc_local_ArithmeticFixture_fneg_value_n0);

double hxc_method_ArithmeticFixture_fsub(double hxc_local_ArithmeticFixture_fsub_left_n0, double hxc_local_ArithmeticFixture_fsub_right_n1);

uint8_t hxc_method_ArithmeticFixture_i32ToU8(int32_t hxc_local_ArithmeticFixture_i32ToU8_value_n0);

uint16_t hxc_method_ArithmeticFixture_i64ToU16(int64_t hxc_local_ArithmeticFixture_i64ToU16_value_n0);

int32_t hxc_method_ArithmeticFixture_i8ToI32(int8_t hxc_local_ArithmeticFixture_i8ToI32_value_n0);

int32_t hxc_method_ArithmeticFixture_iadd(int32_t hxc_local_ArithmeticFixture_iadd_left_n0, int32_t hxc_local_ArithmeticFixture_iadd_right_n1);

int32_t hxc_method_ArithmeticFixture_iand(int32_t hxc_local_ArithmeticFixture_iand_left_n0, int32_t hxc_local_ArithmeticFixture_iand_right_n1);

double hxc_method_ArithmeticFixture_idiv(int32_t hxc_local_ArithmeticFixture_idiv_left_n0, int32_t hxc_local_ArithmeticFixture_idiv_right_n1);

bool hxc_method_ArithmeticFixture_iless(int32_t hxc_local_ArithmeticFixture_iless_left_n0, int32_t hxc_local_ArithmeticFixture_iless_right_n1);

int32_t hxc_method_ArithmeticFixture_imod(int32_t hxc_local_ArithmeticFixture_imod_left_n0, int32_t hxc_local_ArithmeticFixture_imod_right_n1);

int32_t hxc_method_ArithmeticFixture_imul(int32_t hxc_local_ArithmeticFixture_imul_left_n0, int32_t hxc_local_ArithmeticFixture_imul_right_n1);

int32_t hxc_method_ArithmeticFixture_ineg(int32_t hxc_local_ArithmeticFixture_ineg_value_n0);

int32_t hxc_method_ArithmeticFixture_inot(int32_t hxc_local_ArithmeticFixture_inot_value_n0);

int32_t hxc_method_ArithmeticFixture_ior(int32_t hxc_local_ArithmeticFixture_ior_left_n0, int32_t hxc_local_ArithmeticFixture_ior_right_n1);

int32_t hxc_method_ArithmeticFixture_ishl(int32_t hxc_local_ArithmeticFixture_ishl_left_n0, int32_t hxc_local_ArithmeticFixture_ishl_right_n1);

int32_t hxc_method_ArithmeticFixture_ishr(int32_t hxc_local_ArithmeticFixture_ishr_left_n0, int32_t hxc_local_ArithmeticFixture_ishr_right_n1);

int32_t hxc_method_ArithmeticFixture_isub(int32_t hxc_local_ArithmeticFixture_isub_left_n0, int32_t hxc_local_ArithmeticFixture_isub_right_n1);

int32_t hxc_method_ArithmeticFixture_iushr(int32_t hxc_local_ArithmeticFixture_iushr_left_n0, int32_t hxc_local_ArithmeticFixture_iushr_right_n1);

int32_t hxc_method_ArithmeticFixture_ixor(int32_t hxc_local_ArithmeticFixture_ixor_left_n0, int32_t hxc_local_ArithmeticFixture_ixor_right_n1);

uint8_t hxc_method_ArithmeticFixture_literalToU8(void);

void hxc_method_ArithmeticFixture_main(void);

uint64_t hxc_method_ArithmeticFixture_u32ToU64(uint32_t hxc_local_ArithmeticFixture_u32ToU64_value_n0);

uint8_t hxc_method_ArithmeticFixture_u32ToU8(uint32_t hxc_local_ArithmeticFixture_u32ToU8_value_n0);

int16_t hxc_method_ArithmeticFixture_u8ToI16(uint8_t hxc_local_ArithmeticFixture_u8ToI16_value_n0);

int32_t hxc_method_ArithmeticFixture_u8ToI32(uint8_t hxc_local_ArithmeticFixture_u8ToI32_value_n0);

uint32_t hxc_method_ArithmeticFixture_uadd(uint32_t hxc_local_ArithmeticFixture_uadd_left_n0, uint32_t hxc_local_ArithmeticFixture_uadd_right_n1);

uint32_t hxc_method_ArithmeticFixture_umod(uint32_t hxc_local_ArithmeticFixture_umod_left_n0, uint32_t hxc_local_ArithmeticFixture_umod_right_n1);

int32_t hxc_method_ArithmeticFixture_update(int32_t hxc_local_ArithmeticFixture_update_value_n0);

uint32_t hxc_method_ArithmeticFixture_ushl(uint32_t hxc_local_ArithmeticFixture_ushl_left_n0, int32_t hxc_local_ArithmeticFixture_ushl_right_n1);

uint32_t hxc_method_ArithmeticFixture_ushr(uint32_t hxc_local_ArithmeticFixture_ushr_left_n0, int32_t hxc_local_ArithmeticFixture_ushr_right_n1);

#endif /* HXC_GENERATED_PATH_696E636C7564652F6878632F70726F6772616D2E68_INCLUDED */
