#include "hxc/program.h"

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_collisionTrace(void)
{
  uint8_t hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_storage_n0[16384] = { 0 };
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_storage_n0;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_length_n1 = sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_storage_n0) / sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_storage_n0[0]);
  hxc_method_caxecraft_domain_CaxecraftTrace_makeFloor(hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_length_n1);
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n0 = hxc_method_caxecraft_domain_PlayerPhysics_player(5.5, 1.0, 5.5);
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n0;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2;
  struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n2 = hxc_method_caxecraft_domain_PlayerPhysics_input(1.0, 0.5, false);
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n3 = hxc_method_caxecraft_domain_PlayerPhysics_step(hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n2);
  hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n3;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n4 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2;
  struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n5 = hxc_method_caxecraft_domain_PlayerPhysics_input(0.0, 0.0, true);
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n6 = hxc_method_caxecraft_domain_PlayerPhysics_step(hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n4, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n5);
  hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n6;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n7 = &hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n8 = *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n7;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n8 * 1000.0);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n9 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n10 = &hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n11 = *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n10;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n12 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n9, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n11 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n12;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n13 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n14 = &hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n15 = *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n14;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n16 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n13, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n15 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n16;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n17 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n18 = &hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityY_n2;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n19 = *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n18;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n20 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n17, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n19 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n20;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_groundedCode_n4 = 0;
  bool *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n21 = &hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_state_n2.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_grounded_n0;
  bool hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n22 = *hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Daddress_n21;
  if (hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n22)
  {
    hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_groundedCode_n4 = 1;
  }
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n23 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_hash_n3;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n24 = hxc_local_caxecraft_domain_CaxecraftTrace_collisionTrace_groundedCode_n4;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n25 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n23, hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_loadzx2Dresult_n24);
  return hxc_temp_caxecraft_domain_CaxecraftTrace_collisionTrace_callzx2Dresult_n25;
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_editTrace(void)
{
  uint8_t hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_storage_n0[16384] = { 0 };
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_storage_n0;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1 = sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_storage_n0) / sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_storage_n0[0]);
  hxc_method_caxecraft_domain_World_generate(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1, 324508639);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n0 = hxc_method_caxecraft_domain_World_coord(4, 10, 4);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_target_n2 = hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n0;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n1 = hxc_method_caxecraft_domain_World_coord(4, 9, 4);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_base_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n1;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n2 = hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_base_n3;
  hxc_method_caxecraft_domain_World_remove(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n2);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n3 = hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_target_n2;
  enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_enumzx2Dresult_n4 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Stone_n3;
  hxc_method_caxecraft_domain_World_place(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n3, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_enumzx2Dresult_n4);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n5 = hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_target_n2;
  enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_enumzx2Dresult_n6 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Dirt_n2;
  hxc_method_caxecraft_domain_World_place(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n5, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_enumzx2Dresult_n6);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n7 = hxc_method_caxecraft_domain_World_stateHash(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n8 = hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_target_n2;
  enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n9 = hxc_method_caxecraft_domain_World_query(hxc_local_caxecraft_domain_CaxecraftTrace_editTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_loadzx2Dresult_n8);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n10 = hxc_method_caxecraft_domain_World_kindCode(hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n9);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n11 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n7, hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n10);
  return hxc_temp_caxecraft_domain_CaxecraftTrace_editTrace_callzx2Dresult_n11;
}

void hxc_method_caxecraft_domain_CaxecraftTrace_makeFloor(uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_n0, size_t hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_length_n0)
{
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_borrow_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_n0;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_cells_borrow_length_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_length_n0;
  (void)hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_borrow_n1;
  (void)hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_cells_borrow_length_n1;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_zz_n2 = 0;
  while (1)
  {
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n0 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_zz_n2;
    if (!(hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n0 < 32))
    {
      break;
    }
    int32_t hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_x_n3 = 0;
    while (1)
    {
      int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_x_n3;
      if (!(hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n1 < 32))
      {
        break;
      }
      int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n2 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_x_n3;
      int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n3 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_zz_n2;
      struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_callzx2Dresult_n4 = hxc_method_caxecraft_domain_World_coord(hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n2, 0, hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_loadzx2Dresult_n3);
      enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_enumzx2Dresult_n5 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Stone_n3;
      hxc_method_caxecraft_domain_World_replace(hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_n0, hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_cells_length_n0, hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_callzx2Dresult_n4, hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_enumzx2Dresult_n5);
      int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_incrementzx2Dloadzx2Dresult_n6 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_x_n3;
      hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_x_n3 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_incrementzx2Dloadzx2Dresult_n6, 1);
    }
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_incrementzx2Dloadzx2Dresult_n7 = hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_zz_n2;
    hxc_local_caxecraft_domain_CaxecraftTrace_makeFloor_zz_n2 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_CaxecraftTrace_makeFloor_incrementzx2Dloadzx2Dresult_n7, 1);
  }
  return;
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_mix(int32_t hxc_local_caxecraft_domain_CaxecraftTrace_mix_hash_n0, int32_t hxc_local_caxecraft_domain_CaxecraftTrace_mix_value_n1)
{
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dxor(hxc_local_caxecraft_domain_CaxecraftTrace_mix_hash_n0, hxc_local_caxecraft_domain_CaxecraftTrace_mix_value_n1), 16777619);
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_propertyTrace(int32_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0)
{
  uint8_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_storage_n1[16384] = { 0 };
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_storage_n1;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2 = sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_storage_n1) / sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_storage_n1[0]);
  hxc_method_caxecraft_domain_World_generate(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 1103515245), 12345));
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_x_n3 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 17), 5), 31);
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_zz_n4 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 29), 11), 31);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n0 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_x_n3;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_zz_n4;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n2 = hxc_method_caxecraft_domain_World_coord(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n0, 14, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n1);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_edit_n5 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n2;
  if (hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 1) == 0)
  {
    struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n3 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_edit_n5;
    enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_enumzx2Dresult_n4 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Dirt_n2;
    hxc_method_caxecraft_domain_World_place(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n3, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_enumzx2Dresult_n4);
  }
  else
  {
    struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n5 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_edit_n5;
    enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_enumzx2Dresult_n6 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Stone_n3;
    hxc_method_caxecraft_domain_World_place(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n5, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_enumzx2Dresult_n6);
  }
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n7 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_x_n3;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n8 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_zz_n4;
  struct hxc_type_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n9 = hxc_method_caxecraft_domain_VoxelRaycast_trace(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, (double)hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n7 + 0.5, 15.5, (double)hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n8 + 0.5, 0.25, -1.0, 0.5, 24.0);
  struct hxc_type_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n9;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n8 = 0.0;
  if (hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 1) == 0)
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n8 = 1.0;
  }
  else
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n8 = -1.0;
  }
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dloadzx2Dresult_n10 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n8;
  double hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_moveX_n7 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dloadzx2Dresult_n10;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n10 = 0.0;
  if (hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 2) == 0)
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n10 = 0.5;
  }
  else
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n10 = -0.5;
  }
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dloadzx2Dresult_n11 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dresult_n10;
  double hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_movezZ_n9 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_conditionalzx2Dloadzx2Dresult_n11;
  bool hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_jump_n11 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 4) != 0;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n12 = hxc_method_caxecraft_domain_PlayerPhysics_player(1.5 + (double)hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 3), 14.0, 1.5 + (double)hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Ebitzx2Dand(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eunsignedzx2Dshiftzx2Drightzx2Emasked(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_seed_n0, 2), 3));
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n12;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n13 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n14 = hxc_method_caxecraft_domain_PlayerPhysics_recoverSpawn(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n13);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n14;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n15 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n16 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_moveX_n7;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n17 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_movezZ_n9;
  bool hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n18 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_jump_n11;
  struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n19 = hxc_method_caxecraft_domain_PlayerPhysics_input(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n16, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n17, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n18);
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n20 = hxc_method_caxecraft_domain_PlayerPhysics_step(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n15, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n19);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n20;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n21 = hxc_method_caxecraft_domain_World_stateHash(hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_n2, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_cells_length_n2);
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n21;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hitCode_n14 = 0;
  bool *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n22 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_hit_n4;
  bool hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n23 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n22;
  if (hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n23)
  {
    hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hitCode_n14 = 1;
  }
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n24 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n25 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hitCode_n14;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n26 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n24, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n25);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n26;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n27 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n28 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_cellX_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n29 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n28;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n30 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n27, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n29);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n30;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n31 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n32 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_cellY_n1;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n33 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n32;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n34 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n31, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n33);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n34;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n35 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n36 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_cellzZ_n2;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n37 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n36;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n38 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n35, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n37);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n38;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n39 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n40 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_ray_n6.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_visited_n11;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n41 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n40;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n42 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n39, hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n41);
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n42;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n43 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n44 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n45 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n44;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n46 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n43, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n45 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n46;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n47 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n48 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n49 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n48;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n50 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n47, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n49 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13 = hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n50;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n51 = hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_hash_n13;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n52 = &hxc_local_caxecraft_domain_CaxecraftTrace_propertyTrace_state_n12.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n53 = *hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Daddress_n52;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n54 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_loadzx2Dresult_n51, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n53 * 1000.0));
  return hxc_temp_caxecraft_domain_CaxecraftTrace_propertyTrace_callzx2Dresult_n54;
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_rayTrace(void)
{
  uint8_t hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_storage_n0[16384] = { 0 };
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_cells_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_storage_n0;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_cells_length_n1 = sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_storage_n0) / sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_storage_n0[0]);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n0 = hxc_method_caxecraft_domain_World_coord(8, 8, 8);
  enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_enumzx2Dresult_n1 = hxc_field_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_case_Stone_n3;
  hxc_method_caxecraft_domain_World_replace(hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_cells_length_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n0, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_enumzx2Dresult_n1);
  struct hxc_type_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n2 = hxc_method_caxecraft_domain_VoxelRaycast_trace(hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_cells_length_n1, 2.5, 8.5, 8.5, 1.0, 0.0, 0.0, 12.0);
  struct hxc_type_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n2;
  bool *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n3 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_hit_n4;
  bool hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n4 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n3;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dresult_n4 = 0;
  if (hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n4)
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dresult_n4 = 1;
  }
  else
  {
    hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dresult_n4 = 0;
  }
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dloadzx2Dresult_n5 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dresult_n4;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_conditionalzx2Dloadzx2Dresult_n5;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n6 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n7 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_cellX_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n8 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n7;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n9 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n6, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n8);
  hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n9;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n10 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n11 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_previousX_n8;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n12 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n11;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n13 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n10, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n12);
  hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n13;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n14 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n15 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_normalX_n5;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n16 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n15;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n17 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n14, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n16);
  hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n17;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n18 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3;
  double *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n19 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_distance_n3;
  double hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n20 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n19;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n21 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n18, hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n20 * 1000.0));
  hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3 = hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n21;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n22 = hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hash_n3;
  int32_t *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n23 = &hxc_local_caxecraft_domain_CaxecraftTrace_rayTrace_hit_n2.hxc_field_compiler_closedzx2Drecord_4b64390e14c7ed11d116777a42df194773441386f376547df0b7040b6780ecdd_visited_n11;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n24 = *hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Daddress_n23;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n25 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_loadzx2Dresult_n22, hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_recordzx2Dfieldzx2Dloadzx2Dresult_n24);
  return hxc_temp_caxecraft_domain_CaxecraftTrace_rayTrace_callzx2Dresult_n25;
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_runTrace(void)
{
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n0 = hxc_method_caxecraft_domain_CaxecraftTrace_terrainTrace();
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0 = hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n2 = hxc_method_caxecraft_domain_CaxecraftTrace_editTrace();
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n3 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n2);
  hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0 = hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n3;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n4 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n5 = hxc_method_caxecraft_domain_CaxecraftTrace_rayTrace();
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n6 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n4, hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n5);
  hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0 = hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n6;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n7 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0;
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n8 = hxc_method_caxecraft_domain_CaxecraftTrace_collisionTrace();
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n9 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n7, hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n8);
  hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0 = hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n9;
  int32_t hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_seed_n1 = 0;
  while (1)
  {
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n10 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_seed_n1;
    if (!(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n10 < 32))
    {
      break;
    }
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n11 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0;
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n12 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_seed_n1;
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n13 = hxc_method_caxecraft_domain_CaxecraftTrace_propertyTrace(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n12);
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n14 = hxc_method_caxecraft_domain_CaxecraftTrace_mix(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n11, hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n13);
    hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0 = hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_callzx2Dresult_n14;
    int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_incrementzx2Dloadzx2Dresult_n15 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_seed_n1;
    hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_seed_n1 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_incrementzx2Dloadzx2Dresult_n15, 1);
  }
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n16 = hxc_local_caxecraft_domain_CaxecraftTrace_runTrace_hash_n0;
  return hxc_temp_caxecraft_domain_CaxecraftTrace_runTrace_loadzx2Dresult_n16;
}

int32_t hxc_method_caxecraft_domain_CaxecraftTrace_terrainTrace(void)
{
  uint8_t hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_storage_n0[16384] = { 0 };
  uint8_t *hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_n1 = hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_storage_n0;
  size_t hxc_temp_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_length_n1 = sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_storage_n0) / sizeof(hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_storage_n0[0]);
  hxc_method_caxecraft_domain_World_generate(hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_length_n1, 324508639);
  int32_t hxc_temp_caxecraft_domain_CaxecraftTrace_terrainTrace_callzx2Dresult_n0 = hxc_method_caxecraft_domain_World_stateHash(hxc_local_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_n1, hxc_temp_caxecraft_domain_CaxecraftTrace_terrainTrace_cells_length_n1);
  return hxc_temp_caxecraft_domain_CaxecraftTrace_terrainTrace_callzx2Dresult_n0;
}
