#include "hxc/program.h"

double hxc_method_caxecraft_domain_PlayerPhysics_abs(double hxc_local_caxecraft_domain_PlayerPhysics_abs_value_n0)
{
  if (hxc_local_caxecraft_domain_PlayerPhysics_abs_value_n0 < 0.0)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_abs_blockzx2Dlabel_ifzx2Dtrue_n0;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_abs_blockzx2Dlabel_ifzx2Dfalse_n1;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_abs_blockzx2Dlabel_ifzx2Dtrue_n0:
    ;
  return -hxc_local_caxecraft_domain_PlayerPhysics_abs_value_n0;
hxc_temp_caxecraft_domain_PlayerPhysics_abs_blockzx2Dlabel_ifzx2Dfalse_n1:
    ;
  return hxc_local_caxecraft_domain_PlayerPhysics_abs_value_n0;
}

int32_t hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(double hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_value_n0)
{
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_truncated_n1 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_value_n0);
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n0 = hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_truncated_n1;
  if (hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_value_n0 < (double)hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n0)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_blockzx2Dlabel_ifzx2Dtrue_n0;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_blockzx2Dlabel_ifzx2Dfalse_n1;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_blockzx2Dlabel_ifzx2Dtrue_n0:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_truncated_n1;
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Esubtractzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n1, 1);
hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_blockzx2Dlabel_ifzx2Dfalse_n1:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n2 = hxc_local_caxecraft_domain_PlayerPhysics_floorToInt_truncated_n1;
  return hxc_temp_caxecraft_domain_PlayerPhysics_floorToInt_loadzx2Dresult_n2;
}

struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_method_caxecraft_domain_PlayerPhysics_input(double hxc_local_caxecraft_domain_PlayerPhysics_input_moveX_n0, double hxc_local_caxecraft_domain_PlayerPhysics_input_movezZ_n1, bool hxc_local_caxecraft_domain_PlayerPhysics_input_jump_n2)
{
  struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_temp_caxecraft_domain_PlayerPhysics_input_recordzx2Dresult_n0 = (struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09){ .hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_jump_n0 = hxc_local_caxecraft_domain_PlayerPhysics_input_jump_n2, .hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_moveX_n1 = hxc_local_caxecraft_domain_PlayerPhysics_input_moveX_n0, .hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_movezZ_n2 = hxc_local_caxecraft_domain_PlayerPhysics_input_movezZ_n1 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_input_recordzx2Dresult_n0;
}

struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_method_caxecraft_domain_PlayerPhysics_moveAxis(uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_n0, size_t hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_length_n0, double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_x_n1, double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_y_n2, double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_zz_n3, double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_delta_n4, int32_t hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_axis_n5)
{
  uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_borrow_n6 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_n0;
  size_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_cells_borrow_length_n6 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_length_n0;
  (void)hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_borrow_n6;
  (void)hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_cells_borrow_length_n6;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_callzx2Dresult_n0 = hxc_method_caxecraft_domain_PlayerPhysics_abs(hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_delta_n4);
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_magnitude_n7 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_callzx2Dresult_n0;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n1 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_magnitude_n7;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n1 == 0.0)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n0;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n1;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n0:
    ;
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_recordzx2Dresult_n2 = (struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5){ .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0 = false, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_x_n1, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_y_n2, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_zz_n3 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_recordzx2Dresult_n2;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n1:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n3 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_magnitude_n7;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Etozx2Ei32zx2Esaturating(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe(hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n3, 0.20));
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n4 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n5 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_magnitude_n7;
  if ((double)hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n4 * 0.20 < hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n5)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n2;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n3;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n2:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_incrementzx2Dloadzx2Dresult_n6 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_incrementzx2Dloadzx2Dresult_n6, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n3;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n3:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n7 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n7 < 1)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n4;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n5;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n4:
    ;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8 = 1;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n5;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n5:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n8 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_increment_n9 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ef64zx2Edividezx2Ezzerozx2Dsafe(hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_delta_n4, (double)hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n8);
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentX_n10 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_x_n1;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentY_n11 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_y_n2;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentzZ_n12 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_zz_n3;
  bool hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_blocked_n13 = false;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_stepIndex_n14 = 0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dcondition_n6;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dcondition_n6:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n9 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_stepIndex_n14;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n10 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_count_n8;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n9 < hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n10)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dbody_n7;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dexit_n8;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dbody_n7:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n16 = 0.0;
  if (hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_axis_n5 == 0)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n9;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n10;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dexit_n8:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n31 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentX_n10;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n32 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentY_n11;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n33 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentzZ_n12;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n34 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_blocked_n13;
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_recordzx2Dresult_n35 = (struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5){ .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n34, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n31, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n32, .hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n33 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_recordzx2Dresult_n35;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n9:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n11 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentX_n10;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n12 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_increment_n9;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n16 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n11 + hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n12;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n11;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n10:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n13 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentX_n10;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n16 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n13;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n11;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n11:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n14 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n16;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateX_n15 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n14;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n18 = 0.0;
  if (hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_axis_n5 == 1)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n12;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n13;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n12:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n15 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentY_n11;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n16 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_increment_n9;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n18 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n15 + hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n16;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n14;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n13:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n17 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentY_n11;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n18 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n17;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n14;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n14:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n18 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n18;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateY_n17 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n18;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n20 = 0.0;
  if (hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_axis_n5 == 2)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n15;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n16;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dtrue_n15:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n19 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentzZ_n12;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n20 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_increment_n9;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n20 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n19 + hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n20;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n17;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Dfalse_n16:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n21 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentzZ_n12;
  hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n20 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n21;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n17;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_conditionalzx2Djoin_n17:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n22 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dresult_n20;
  double hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidatezZ_n19 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_conditionalzx2Dloadzx2Dresult_n22;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n23 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateX_n15;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n24 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateY_n17;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n25 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidatezZ_n19;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_callzx2Dresult_n26 = hxc_method_caxecraft_domain_PlayerPhysics_overlaps(hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n23, hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n24, hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n25);
  if (hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_callzx2Dresult_n26)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n18;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n19;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Dtrue_n18:
    ;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_blocked_n13 = true;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dexit_n8;
hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_ifzx2Djoin_n19:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n27 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateX_n15;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentX_n10 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n27;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n28 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidateY_n17;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentY_n11 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n28;
  double hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n29 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_candidatezZ_n19;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_currentzZ_n12 = hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_loadzx2Dresult_n29;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_incrementzx2Dloadzx2Dresult_n30 = hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_stepIndex_n14;
  hxc_local_caxecraft_domain_PlayerPhysics_moveAxis_stepIndex_n14 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_incrementzx2Dloadzx2Dresult_n30, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_moveAxis_blockzx2Dlabel_whilezx2Dcondition_n6;
}

bool hxc_method_caxecraft_domain_PlayerPhysics_overlaps(uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_n0, size_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_length_n0, double hxc_local_caxecraft_domain_PlayerPhysics_overlaps_x_n1, double hxc_local_caxecraft_domain_PlayerPhysics_overlaps_y_n2, double hxc_local_caxecraft_domain_PlayerPhysics_overlaps_zz_n3)
{
  uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_borrow_n4 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_n0;
  size_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_cells_borrow_length_n4 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_length_n0;
  (void)hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_borrow_n4;
  (void)hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_cells_borrow_length_n4;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n0 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_x_n1 - 0.30 + 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumX_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n0;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n1 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_x_n1 + 0.30 - 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumX_n6 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n1;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n2 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_y_n2 + 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumY_n7 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n2;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n3 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_y_n2 + 1.80 - 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumY_n8 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n3;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n4 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_zz_n3 - 0.30 + 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumzZ_n9 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n4;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n5 = hxc_method_caxecraft_domain_PlayerPhysics_floorToInt(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_zz_n3 + 0.30 - 0.0001);
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumzZ_n10 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n5;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n6 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumY_n7;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockY_n11 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n6;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n0;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n0:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n7 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockY_n11;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n8 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumY_n8;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n7 <= hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n8)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n1;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n2;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n1:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n9 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumzZ_n9;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockzZ_n12 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n9;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n3;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n2:
    ;
  return false;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n3:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n10 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockzZ_n12;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n11 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumzZ_n10;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n10 <= hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n11)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n4;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n5;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n4:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n12 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_minimumX_n5;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockX_n13 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n12;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n6;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n5:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n27 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockY_n11;
  hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockY_n11 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n27, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n0;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n6:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n13 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockX_n13;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n14 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_maximumX_n6;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n13 <= hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n14)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n7;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n8;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dbody_n7:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n15 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockX_n13;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n16 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockY_n11;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n17 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockzZ_n12;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n18 = hxc_method_caxecraft_domain_World_coord(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n15, hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n16, hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n17);
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_local_caxecraft_domain_PlayerPhysics_overlaps_coord_n14 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n18;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n19 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_coord_n14;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n20 = hxc_method_caxecraft_domain_World_contains(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n19);
  bool hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_shortzx2Dcircuitzx2Dresult_n15 = !hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n20;
  if (!hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n20)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n10;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n9;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dexit_n8:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n26 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockzZ_n12;
  hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockzZ_n12 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n26, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n3;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n9:
    ;
  struct hxc_type_compiler_closedzx2Drecord_4aec2e39ec8810b7a1e1fcaf6d9e8d814f0669cbda1d84c602ab5badb7373793 hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n21 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_coord_n14;
  enum hxc_type_compiler_haxezx2Denum_60d3cdd205065bf6cff636ab4b457e3916ca25d552c40826dfb12cd3899e5c88_value hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n22 = hxc_method_caxecraft_domain_World_query(hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_overlaps_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_loadzx2Dresult_n21);
  bool hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n23 = hxc_method_caxecraft_domain_World_isSolid(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n22);
  hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_shortzx2Dcircuitzx2Dresult_n15 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_callzx2Dresult_n23;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n10;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n10:
    ;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_shortzx2Dcircuitzx2Dloadzx2Dresult_n24 = hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_shortzx2Dcircuitzx2Dresult_n15;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_shortzx2Dcircuitzx2Dloadzx2Dresult_n24)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_ifzx2Dtrue_n11;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_ifzx2Djoin_n12;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_ifzx2Dtrue_n11:
    ;
  return true;
hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_ifzx2Djoin_n12:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n25 = hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockX_n13;
  hxc_local_caxecraft_domain_PlayerPhysics_overlaps_blockX_n13 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_incrementzx2Dloadzx2Dresult_n25, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_overlaps_blockzx2Dlabel_whilezx2Dcondition_n6;
}

struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_method_caxecraft_domain_PlayerPhysics_player(double hxc_local_caxecraft_domain_PlayerPhysics_player_x_n0, double hxc_local_caxecraft_domain_PlayerPhysics_player_y_n1, double hxc_local_caxecraft_domain_PlayerPhysics_player_zz_n2)
{
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_PlayerPhysics_player_recordzx2Dresult_n0 = (struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001){ .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_grounded_n0 = false, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityX_n1 = 0.0, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityY_n2 = 0.0, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityzZ_n3 = 0.0, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4 = hxc_local_caxecraft_domain_PlayerPhysics_player_x_n0, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5 = hxc_local_caxecraft_domain_PlayerPhysics_player_y_n1, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6 = hxc_local_caxecraft_domain_PlayerPhysics_player_zz_n2 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_player_recordzx2Dresult_n0;
}

struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_method_caxecraft_domain_PlayerPhysics_recoverSpawn(uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_n0, size_t hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_length_n0, struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1)
{
  uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_borrow_n2 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_n0;
  size_t hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_borrow_length_n2 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_length_n0;
  (void)hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_borrow_n2;
  (void)hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_borrow_length_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n0 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5;
  double hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_recoveredY_n3 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n0;
  int32_t hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_attempts_n4 = 0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dcondition_n0;
hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dcondition_n0:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n1 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n2 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_recoveredY_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n3 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_callzx2Dresult_n4 = hxc_method_caxecraft_domain_PlayerPhysics_overlaps(hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n1, hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n2, hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n3);
  bool hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_shortzx2Dcircuitzx2Dresult_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_callzx2Dresult_n4;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_callzx2Dresult_n4)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n3;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n4;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dbody_n1:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_compoundzx2Dloadzx2Dresult_n7 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_recoveredY_n3;
  hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_recoveredY_n3 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_compoundzx2Dloadzx2Dresult_n7 + 1.0;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_incrementzx2Dloadzx2Dresult_n8 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_attempts_n4;
  hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_attempts_n4 = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_incrementzx2Dloadzx2Dresult_n8, 1);
  goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dcondition_n0;
hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dexit_n2:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n9 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n10 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_recoveredY_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n11 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n12 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityX_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n13 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_state_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityzZ_n3;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dresult_n14 = (struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001){ .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_grounded_n0 = false, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityX_n1 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n12, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityY_n2 = 0.0, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityzZ_n3 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n13, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n9, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n10, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dfieldzx2Dproject_n11 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_recordzx2Dresult_n14;
hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n3:
    ;
  int32_t hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n5 = hxc_local_caxecraft_domain_PlayerPhysics_recoverSpawn_attempts_n4;
  hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_shortzx2Dcircuitzx2Dresult_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_loadzx2Dresult_n5 < 16;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n4;
hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n4:
    ;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_shortzx2Dcircuitzx2Dloadzx2Dresult_n6 = hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_shortzx2Dcircuitzx2Dresult_n5;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_shortzx2Dcircuitzx2Dloadzx2Dresult_n6)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dbody_n1;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_recoverSpawn_blockzx2Dlabel_whilezx2Dexit_n2;
  }
}

struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_method_caxecraft_domain_PlayerPhysics_step(uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, size_t hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1, struct hxc_type_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09 hxc_local_caxecraft_domain_PlayerPhysics_step_command_n2)
{
  uint8_t *hxc_local_caxecraft_domain_PlayerPhysics_step_cells_borrow_n3 = hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0;
  size_t hxc_temp_caxecraft_domain_PlayerPhysics_step_cells_borrow_length_n3 = hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0;
  (void)hxc_local_caxecraft_domain_PlayerPhysics_step_cells_borrow_n3;
  (void)hxc_temp_caxecraft_domain_PlayerPhysics_step_cells_borrow_length_n3;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4 = hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n0 = hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n1 = hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n2 = hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n3 = hxc_method_caxecraft_domain_PlayerPhysics_overlaps(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n1, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n2);
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n3)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n0;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n1;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n0:
    ;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n4 = hxc_method_caxecraft_domain_PlayerPhysics_recoverSpawn(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_original_n1);
  hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4 = hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n4;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n1;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n1:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n5 = hxc_local_caxecraft_domain_PlayerPhysics_step_command_n2.hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_moveX_n1;
  double hxc_local_caxecraft_domain_PlayerPhysics_step_velocityX_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n5 * 4.0;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n6 = hxc_local_caxecraft_domain_PlayerPhysics_step_command_n2.hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_movezZ_n2;
  double hxc_local_caxecraft_domain_PlayerPhysics_step_velocityzZ_n6 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n6 * 4.0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n7 = hxc_local_caxecraft_domain_PlayerPhysics_step_command_n2.hxc_field_compiler_closedzx2Drecord_bc04a64b56baa2f3e6cd72087421c3aca30316ecd3e8002f46391dbd97835c09_jump_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n8 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n7;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dproject_n7)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n2;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n3;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n2:
    ;
  bool *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n8 = &hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_grounded_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n9 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n8;
  hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n8 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n9;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n3;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n3:
    ;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dloadzx2Dresult_n10 = hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n8;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dresult_n9 = 0.0;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dloadzx2Dresult_n10)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Dtrue_n4;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Dfalse_n5;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Dtrue_n4:
    ;
  hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dresult_n9 = 6.5;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Djoin_n6;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Dfalse_n5:
    ;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n11 = &hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityY_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n12 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n11;
  hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dresult_n9 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n12 + -0.9;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Djoin_n6;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_conditionalzx2Djoin_n6:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dloadzx2Dresult_n13 = hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dresult_n9;
  double hxc_local_caxecraft_domain_PlayerPhysics_step_velocityY_n7 = hxc_temp_caxecraft_domain_PlayerPhysics_step_conditionalzx2Dloadzx2Dresult_n13;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n14 = &hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n15 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n14;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n16 = &hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n17 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n16;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n18 = &hxc_local_caxecraft_domain_PlayerPhysics_step_state_n4.hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n19 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n18;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n20 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityX_n5;
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n21 = hxc_method_caxecraft_domain_PlayerPhysics_moveAxis(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n15, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n17, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n19, hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n20 * 0.05, 0);
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_local_caxecraft_domain_PlayerPhysics_step_movedX_n10 = hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n21;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n22 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedX_n10.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n23 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n22;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n24 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedX_n10.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n25 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n24;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n26 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedX_n10.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n27 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n26;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n28 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityzZ_n6;
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n29 = hxc_method_caxecraft_domain_PlayerPhysics_moveAxis(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n23, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n25, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n27, hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n28 * 0.05, 2);
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_local_caxecraft_domain_PlayerPhysics_step_movedzZ_n11 = hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n29;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n30 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedzZ_n11.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n31 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n30;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n32 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedzZ_n11.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n33 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n32;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n34 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedzZ_n11.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n35 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n34;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n36 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityY_n7;
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n37 = hxc_method_caxecraft_domain_PlayerPhysics_moveAxis(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n31, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n33, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n35, hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n36 * 0.05, 1);
  struct hxc_type_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5 hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12 = hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n37;
  bool *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n38 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n39 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n38;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n14 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n39;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n39)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n7;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n8;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Drhs_n7:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n40 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityY_n7;
  hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n14 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n40 <= 0.0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n8;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_shortzx2Dcircuitzx2Djoin_n8:
    ;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dloadzx2Dresult_n41 = hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dresult_n14;
  bool hxc_local_caxecraft_domain_PlayerPhysics_step_grounded_n13 = hxc_temp_caxecraft_domain_PlayerPhysics_step_shortzx2Dcircuitzx2Dloadzx2Dresult_n41;
  bool *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n42 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n43 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n42;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n43)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n9;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n10;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n9:
    ;
  hxc_local_caxecraft_domain_PlayerPhysics_step_velocityY_n7 = 0.0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n10;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n10:
    ;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n44 = hxc_local_caxecraft_domain_PlayerPhysics_step_grounded_n13;
  if (!hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n44)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n11;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n12;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n11:
    ;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n45 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n46 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n45;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n47 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n48 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n47;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n49 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n50 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n49;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n51 = hxc_method_caxecraft_domain_PlayerPhysics_overlaps(hxc_local_caxecraft_domain_PlayerPhysics_step_cells_n0, hxc_local_caxecraft_domain_PlayerPhysics_step_cells_length_n0, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n46, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n48 - 0.02, hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n50);
  hxc_local_caxecraft_domain_PlayerPhysics_step_grounded_n13 = hxc_temp_caxecraft_domain_PlayerPhysics_step_callzx2Dresult_n51;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n12;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n12:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n52 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityX_n5;
  double hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityX_n15 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n52;
  bool *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n53 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedX_n10.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n54 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n53;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n54)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n13;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n14;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n13:
    ;
  hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityX_n15 = 0.0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n14;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n14:
    ;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n55 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityzZ_n6;
  double hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityzZ_n16 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n55;
  bool *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n56 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedzZ_n11.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_blocked_n0;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n57 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n56;
  if (hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n57)
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n15;
  }
  else
  {
    goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n16;
  }
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Dtrue_n15:
    ;
  hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityzZ_n16 = 0.0;
  goto hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n16;
hxc_temp_caxecraft_domain_PlayerPhysics_step_blockzx2Dlabel_ifzx2Djoin_n16:
    ;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n58 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_x_n1;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n59 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n58;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n60 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_y_n2;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n61 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n60;
  double *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n62 = &hxc_local_caxecraft_domain_PlayerPhysics_step_movedY_n12.hxc_field_compiler_closedzx2Drecord_cc8444204c482819cfe6fa9c0e97a06199a6b7b09558fbf67326932221ab97e5_zz_n3;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n63 = *hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Daddress_n62;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n64 = hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityX_n15;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n65 = hxc_local_caxecraft_domain_PlayerPhysics_step_velocityY_n7;
  double hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n66 = hxc_local_caxecraft_domain_PlayerPhysics_step_finalVelocityzZ_n16;
  bool hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n67 = hxc_local_caxecraft_domain_PlayerPhysics_step_grounded_n13;
  struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001 hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dresult_n68 = (struct hxc_type_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001){ .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_grounded_n0 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n67, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityX_n1 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n64, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityY_n2 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n65, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_velocityzZ_n3 = hxc_temp_caxecraft_domain_PlayerPhysics_step_loadzx2Dresult_n66, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_x_n4 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n59, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_y_n5 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n61, .hxc_field_compiler_closedzx2Drecord_e096fe3dbe05d1c9c3f2116889cae7ff854f387b562648a36fb62ef8dc1c1001_zz_n6 = hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dfieldzx2Dloadzx2Dresult_n63 };
  return hxc_temp_caxecraft_domain_PlayerPhysics_step_recordzx2Dresult_n68;
}
