#ifndef HXC_CAXECRAFT_APP_CAXECRAFT_APP_H_INCLUDED
#define HXC_CAXECRAFT_APP_CAXECRAFT_APP_H_INCLUDED

#include "hxc/detail/program_types.h"
#include "hxc/modules/caxecraft/app/TerrainRenderer.h"
#include "hxc/modules/caxecraft/app/WaterRenderer.h"
#include "hxc/modules/caxecraft/input/NavigationInput.h"

struct hxc_caxecraft_app_CaxecraftApp {
  struct hxc_caxecraft_app_TerrainRenderer hxc_terrainRenderer;
  struct hxc_caxecraft_app_WaterRenderer hxc_waterRenderer;
  struct hxc_caxecraft_input_NavigationRepeater hxc_editorNavigation;
};

struct hxc_caxecraft_app_CaxecraftApp_ActorPhaseObservation {
  enum hxc_caxecraft_domain_ActorControllerPhase hxc_phase;
  bool hxc_valid;
};

enum hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_tag {
  hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_NoAvailableInteraction = 0,
  hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_DialogueInteraction = 1,
  hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_StatefulObjectInteraction = 2
};

struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_DialogueInteraction_payload {
  int32_t hxc_id;
};

struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_StatefulObjectInteraction_payload {
  hxc_string hxc_id;
};

union hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_payload {
  struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_DialogueInteraction_payload hxc_DialogueInteraction;
  struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_StatefulObjectInteraction_payload hxc_StatefulObjectInteraction;
};

struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget {
  enum hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_tag hxc_tag;
  union hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget_payload hxc_payload;
};

void hxc_compiler_constructor_caxecraft_app_CaxecraftApp(struct hxc_caxecraft_app_CaxecraftApp *hxc_l_self);

hxc_string hxc_caxecraft_app_CaxecraftApp_campaignLevelLoadFailure(struct hxc_caxecraft_content_CampaignLevelLoadError hxc_l_error);

struct hxc_array_ref *hxc_caxecraft_app_CaxecraftApp_dialogueActorSnapshots(struct hxc_caxecraft_domain_GameSession *hxc_l_session, struct hxc_caxecraft_app_PlayableLevelView *hxc_l_level);

bool hxc_caxecraft_app_CaxecraftApp_dialogueActorsAreValid(struct hxc_caxecraft_domain_GameSession *hxc_l_session, struct hxc_caxecraft_app_PlayableLevelView *hxc_l_level, struct hxc_array_ref *hxc_l_states);

void hxc_caxecraft_app_CaxecraftApp_drawActors(struct Camera3D hxc_l_camera, struct Texture hxc_l_entityTexture, bool hxc_l_entityTextureReady, struct hxc_array_ref *hxc_l_dialogueActors, struct hxc_caxecraft_app_PlayableLevelView *hxc_l_level, struct hxc_caxecraft_domain_Character hxc_l_enemy, int32_t hxc_l_enemyCell, enum hxc_caxecraft_domain_ActorControllerPhase hxc_l_enemyPhase, struct hxc_caxecraft_gameplay_BerryDropState hxc_l_berryDrop);

void hxc_caxecraft_app_CaxecraftApp_drawBreath(int32_t hxc_l_breathTicks, int32_t hxc_l_maximumBreathTicks, int32_t hxc_l_width, int32_t hxc_l_height);

void hxc_caxecraft_app_CaxecraftApp_drawHealth(struct hxc_caxecraft_domain_VitalsState hxc_l_vitals, struct Texture hxc_l_hudTexture, bool hxc_l_hudTextureReady, int32_t hxc_l_width);

void hxc_caxecraft_app_CaxecraftApp_drawHotbar(struct hxc_caxecraft_gameplay_InventoryState hxc_l_inventory, struct Texture hxc_l_hudTexture, bool hxc_l_hudTextureReady, struct Texture hxc_l_itemTexture, bool hxc_l_itemTextureReady, int32_t hxc_l_width, int32_t hxc_l_height);

void hxc_caxecraft_app_CaxecraftApp_drawHud(struct hxc_caxecraft_app_HudView hxc_l_view, struct hxc_caxecraft_app_HudResources hxc_l_resources, struct hxc_caxecraft_content_RuntimeContentRegistry *hxc_l_contentRegistry, struct hxc_caxecraft_localization_RuntimeUiCatalog *hxc_l_uiCatalog);

void hxc_caxecraft_app_CaxecraftApp_drawWrappedText(hxc_string hxc_l_value, int32_t hxc_l_x, int32_t hxc_l_y, int32_t hxc_l_fontSize, int32_t hxc_l_maximumCharacters, int32_t hxc_l_lineHeight, int32_t hxc_l_maximumLines, struct Color hxc_l_color);

struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget hxc_caxecraft_app_CaxecraftApp_nearestAvailableInteraction(struct hxc_caxecraft_domain_GameSession *hxc_l_session, struct hxc_caxecraft_app_PlayableLevelView *hxc_l_level);

struct hxc_caxecraft_app_CaxecraftApp_ActorPhaseObservation hxc_caxecraft_app_CaxecraftApp_observeActorPhase(struct hxc_array_ref *hxc_l_states, int32_t hxc_l_id, enum hxc_caxecraft_domain_ActorControllerPhase hxc_l_fallback);

enum hxc_caxecraft_app_InteractionPrompt hxc_caxecraft_app_CaxecraftApp_promptForAvailableInteraction(struct hxc_caxecraft_app_CaxecraftApp_AvailableInteractionTarget hxc_l_target);

struct hxc_caxecraft_domain_CharacterBody hxc_caxecraft_app_CaxecraftApp_spawnPlayer(const uint8_t *hxc_l_cells, size_t hxc_l_length, struct hxc_caxecraft_scenario_ScenarioTransform hxc_l_transform);

void hxc_caxecraft_app_CaxecraftApp_run(struct hxc_caxecraft_app_CaxecraftApp *hxc_l_self);

#endif /* HXC_CAXECRAFT_APP_CAXECRAFT_APP_H_INCLUDED */
