#ifndef HXC_CAXECRAFT_GAMEPLAY_ITEM_KIND_H_INCLUDED
#define HXC_CAXECRAFT_GAMEPLAY_ITEM_KIND_H_INCLUDED

#include "hxc/detail/program_types.h"

#endif /* HXC_CAXECRAFT_GAMEPLAY_ITEM_KIND_H_INCLUDED */
