package reflaxe.c.lowering;

import reflaxe.c.ast.CAST.CIdentifier;

/**
	Closed authority for fixed names declared by checked-in hxrt headers.

	These names are compiler/runtime ABI facts, never derived from Haxe input.
	Keeping the vocabulary closed prevents runtime dispatch from becoming a raw-C
	symbol escape hatch while still routing every token through CIdentifier.
**/
enum CBodyRuntimeName {
	CBRNStringType;
	CBRNStringCharAt;
	CBRNStringCharCodeAt;
	CBRNStringLength;
	CBRNStringIndexOf;
	CBRNStringLastIndexOf;
	CBRNStringSplit;
	CBRNArrayStringJoin;
	CBRNStringSubstr;
	CBRNStringSubstring;
	CBRNStringRetain;
	CBRNStringRelease;
	CBRNStringReleaseSlot;
	CBRNStringFromScalar;
	CBRNStringFromInt;
	CBRNStringFromFloat;
	CBRNStringConcat;
	CBRNStringToLowerCase;
	CBRNBorrowedCStringType;
	CBRNBorrowedCStringInitializer;
	CBRNStringBorrowCString;
	CBRNBorrowedCStringData;
	CBRNCallCStringType;
	CBRNCallCStringInitializer;
	CBRNStringPrepareCallCString;
	CBRNCallCStringDispose;
	CBRNPrintln;
	CBRNDateTimeWallMilliseconds;
	CBRNDateTimeMonotonicSeconds;
	CBRNDateTimeLocalToMilliseconds;
	CBRNDateTimeTimezoneOffset;
	CBRNStatusType;
	CBRNStatusOk;
	CBRNAbort;
	CBRNDefaultAllocator;
	CBRNAllocatorType;
	CBRNAllocate;
	CBRNFree;
	CBRNGcRootFrameType;
	CBRNGcRootFrameInitializer;
	CBRNGcRootFramePush;
	CBRNGcRootFramePop;
	CBRNGcRootFramePopCleanup;
	CBRNExceptionFrameType;
	CBRNExceptionFrameInitializer;
	CBRNExceptionFramePush;
	CBRNExceptionFrameSetJmp;
	CBRNExceptionFramePayload;
	CBRNExceptionFrameTakePayload;
	CBRNExceptionFramePop;
	CBRNExceptionRaise;
	CBRNExceptionRootSlotUpdate;
	CBRNExceptionCleanupType;
	CBRNExceptionCleanupInitializer;
	CBRNExceptionCleanupPush;
	CBRNExceptionCleanupRun;
	CBRNExceptionCleanupDiscard;
	CBRNGcType;
	CBRNGcThreadType;
	CBRNGcConfigType;
	CBRNGcInitializer;
	CBRNGcThreadInitializer;
	CBRNGcInit;
	CBRNGcAllocate;
	CBRNGcDispose;
	CBRNGcThreadRegister;
	CBRNGcThreadUnregister;
	CBRNArrayCreate;
	CBRNArrayCreateTrivial;
	CBRNArrayInitInPlace;
	CBRNArrayCopy;
	CBRNArrayCopyInPlace;
	CBRNArrayDisposeInPlace;
	CBRNArrayElementOpsType;
	CBRNArrayGetCopy;
	CBRNArrayLength;
	CBRNArrayPopMove;
	CBRNArrayShiftMove;
	CBRNArraySpliceOneDiscard;
	CBRNArraySpliceOneCopy;
	CBRNArraySpliceDiscard;
	CBRNArraySpliceCopy;
	CBRNArrayInsertCopy;
	CBRNArrayPushCopy;
	CBRNArraySetCopy;
	CBRNArraySort;
	CBRNArrayRetain;
	CBRNArrayRelease;
	CBRNArrayReleaseSlot;
	CBRNArrayStoragePushCopy;
	CBRNArrayStorageResize;
	CBRNArrayResizeDefault;
	CBRNArrayValueMember;
	CBRNStringMapCreate;
	CBRNStringMapCreateWithOps;
	CBRNStringMapValueOpsType;
	CBRNStringMapRetain;
	CBRNStringMapRelease;
	CBRNStringMapReleaseSlot;
	CBRNStringMapCopy;
	CBRNStringMapSetCopy;
	CBRNStringMapExists;
	CBRNStringMapGetCopy;
	CBRNStringMapRemove;
	CBRNStringMapClear;
	CBRNStringMapValueIterator;
	CBRNStringMapKeyIterator;
	CBRNStringMapPairIterator;
	CBRNStringMapToString;
	CBRNIteratorCreateArrayValues;
	CBRNIteratorCreateArrayPairs;
	CBRNIteratorRetain;
	CBRNIteratorRelease;
	CBRNIteratorReleaseSlot;
	CBRNIteratorHasNext;
	CBRNIteratorNextMove;
	CBRNIntMapCreate;
	CBRNIntMapRetain;
	CBRNIntMapRelease;
	CBRNIntMapReleaseSlot;
	CBRNIntMapCopy;
	CBRNIntMapSet;
	CBRNIntMapExists;
	CBRNIntMapGet;
	CBRNIntMapRemove;
	CBRNIntMapClear;
	CBRNIntMapValueIterator;
	CBRNIntMapKeyIterator;
	CBRNIntMapPairIterator;
	CBRNIntMapToString;
	CBRNTypedMapTypeDescriptor;
	CBRNTypedMapIdentityHash;
	CBRNTypedMapHashMix;
	CBRNTypedMapInitCollectorOwned;
	CBRNTypedMapCopyInPlace;
	CBRNTypedMapSetCopy;
	CBRNTypedMapExists;
	CBRNTypedMapGetCopy;
	CBRNTypedMapRemove;
	CBRNTypedMapClear;
	CBRNTypedMapValueIterator;
	CBRNTypedMapKeyIterator;
	CBRNTypedMapPairIterator;
	CBRNTypedMapKeyOpsType;
	CBRNTypedMapValueOpsType;
	CBRNIteratorElementOpsType;
	CBRNBytesCreateZeroed;
	CBRNBytesCreateUtf8Copy;
	CBRNBytesLength;
	CBRNBytesGet;
	CBRNBytesSet;
	CBRNBytesSub;
	CBRNBytesBlit;
	CBRNBytesFill;
	CBRNBytesCompare;
	CBRNBytesBorrowMutableCString;
	CBRNBytesGetStringUtf8;
	CBRNBytesRetain;
	CBRNBytesRelease;
	CBRNBytesReleaseSlot;
	CBRNDynamicValueType;
	CBRNDynamicTypeDescriptorType;
	CBRNDynamicTypeAbiVersion;
	CBRNDynamicCategoryNull;
	CBRNDynamicCategoryBool;
	CBRNDynamicCategoryInt;
	CBRNDynamicCategoryFloat;
	CBRNDynamicCategoryString;
	CBRNDynamicCategoryArray;
	CBRNDynamicCategoryObject;
	CBRNDynamicCategoryEnum;
	CBRNDynamicCategoryFunction;
	CBRNDynamicCategoryTypeValue;
	CBRNDynamicStorageInlineNull;
	CBRNDynamicStorageInlineBool;
	CBRNDynamicStorageInlineInt32;
	CBRNDynamicStorageInlineFloat64;
	CBRNDynamicStorageManagedReference;
	CBRNDynamicStorageManagedWrapper;
	CBRNDynamicStorageStaticToken;
	CBRNDynamicInvalidInitializer;
	CBRNDynamicInitNull;
	CBRNDynamicInitBool;
	CBRNDynamicInitInt32;
	CBRNDynamicInitFloat64;
	CBRNDynamicInitManagedReference;
	CBRNDynamicInitManagedWrapper;
	CBRNDynamicInitStaticToken;
	CBRNDynamicReadBool;
	CBRNDynamicReadInt32;
	CBRNDynamicReadFloat64;
	CBRNDynamicReadManagedReference;
	CBRNDynamicReadManagedWrapper;
	CBRNDynamicReadStaticToken;
	CBRNDynamicManagedPayload;
	CBRNDynamicTypeField;
	CBRNDynamicActiveStorageField;
	CBRNDynamicPayloadField;
	CBRNDynamicPayloadObjectField;
	CBRNDynamicPayloadBoolField;
	CBRNDynamicPayloadInt32Field;
	CBRNDynamicPayloadFloat64Field;
	CBRNDynamicDescriptorAbiVersionField;
	CBRNDynamicDescriptorTypeIdField;
	CBRNDynamicDescriptorCategoryField;
	CBRNDynamicDescriptorStorageField;
}

class CBodyRuntimeNames {
	public static function identifier(name:CBodyRuntimeName):CIdentifier {
		return new CIdentifier(switch name {
			case CBRNStringType: "hxc_string";
			case CBRNStringCharAt: "hxc_string_char_at";
			case CBRNStringCharCodeAt: "hxc_string_char_code_at";
			case CBRNStringLength: "hxc_string_haxe_length";
			case CBRNStringIndexOf: "hxc_string_index_of";
			case CBRNStringLastIndexOf: "hxc_string_last_index_of";
			case CBRNStringSplit: "hxc_string_split";
			case CBRNArrayStringJoin: "hxc_array_string_join";
			case CBRNStringSubstr: "hxc_string_substr";
			case CBRNStringSubstring: "hxc_string_substring";
			case CBRNStringRetain: "hxc_string_retain";
			case CBRNStringRelease: "hxc_string_release";
			case CBRNStringReleaseSlot: "hxc_string_release_slot";
			case CBRNStringFromScalar: "hxc_string_from_scalar";
			case CBRNStringFromInt: "hxc_string_from_int32";
			case CBRNStringFromFloat: "hxc_string_from_float64";
			case CBRNStringConcat: "hxc_string_concat_ref";
			case CBRNStringToLowerCase: "hxc_string_to_lower_case";
			case CBRNBorrowedCStringType: "hxc_borrowed_cstring";
			case CBRNBorrowedCStringInitializer: "HXC_BORROWED_CSTRING_INITIALIZER";
			case CBRNStringBorrowCString: "hxc_string_borrow_cstring";
			case CBRNBorrowedCStringData: "data";
			case CBRNCallCStringType: "hxc_call_cstring";
			case CBRNCallCStringInitializer: "HXC_CALL_CSTRING_INITIALIZER";
			case CBRNStringPrepareCallCString: "hxc_string_prepare_call_cstring";
			case CBRNCallCStringDispose: "hxc_call_cstring_dispose";
			case CBRNPrintln: "hxc_io_println";
			case CBRNDateTimeWallMilliseconds: "hxc_date_time_wall_milliseconds";
			case CBRNDateTimeMonotonicSeconds: "hxc_date_time_monotonic_seconds";
			case CBRNDateTimeLocalToMilliseconds: "hxc_date_time_local_to_milliseconds";
			case CBRNDateTimeTimezoneOffset: "hxc_date_time_timezone_offset";
			case CBRNStatusType: "hxc_status";
			case CBRNStatusOk: "HXC_STATUS_OK";
			case CBRNAbort: "abort";
			case CBRNDefaultAllocator: "hxc_default_allocator";
			case CBRNAllocatorType: "hxc_allocator";
			case CBRNAllocate: "hxc_alloc";
			case CBRNFree: "hxc_free";
			case CBRNGcRootFrameType: "hxc_gc_root_frame";
			case CBRNGcRootFrameInitializer: "HXC_GC_ROOT_FRAME_INITIALIZER";
			case CBRNGcRootFramePush: "hxc_gc_root_frame_push";
			case CBRNGcRootFramePop: "hxc_gc_root_frame_pop";
			case CBRNGcRootFramePopCleanup: "hxc_gc_root_frame_pop_cleanup";
			case CBRNExceptionFrameType: "hxc_exception_frame";
			case CBRNExceptionFrameInitializer: "HXC_EXCEPTION_FRAME_INITIALIZER";
			case CBRNExceptionFramePush: "hxc_exception_frame_push";
			case CBRNExceptionFrameSetJmp: "HXC_EXCEPTION_SETJMP";
			case CBRNExceptionFramePayload: "hxc_exception_frame_payload";
			case CBRNExceptionFrameTakePayload: "hxc_exception_frame_take_payload";
			case CBRNExceptionFramePop: "hxc_exception_frame_pop";
			case CBRNExceptionRaise: "hxc_exception_raise";
			case CBRNExceptionRootSlotUpdate: "hxc_exception_root_slot_update";
			case CBRNExceptionCleanupType: "hxc_exception_cleanup";
			case CBRNExceptionCleanupInitializer: "HXC_EXCEPTION_CLEANUP_INITIALIZER";
			case CBRNExceptionCleanupPush: "hxc_exception_cleanup_push";
			case CBRNExceptionCleanupRun: "hxc_exception_cleanup_run";
			case CBRNExceptionCleanupDiscard: "hxc_exception_cleanup_discard";
			case CBRNGcType: "hxc_gc";
			case CBRNGcThreadType: "hxc_gc_thread";
			case CBRNGcConfigType: "hxc_gc_config";
			case CBRNGcInitializer: "HXC_GC_INITIALIZER";
			case CBRNGcThreadInitializer: "HXC_GC_THREAD_INITIALIZER";
			case CBRNGcInit: "hxc_gc_init";
			case CBRNGcAllocate: "hxc_gc_allocate";
			case CBRNGcDispose: "hxc_gc_dispose";
			case CBRNGcThreadRegister: "hxc_gc_thread_register";
			case CBRNGcThreadUnregister: "hxc_gc_thread_unregister";
			case CBRNArrayCreate: "hxc_array_ref_create";
			case CBRNArrayCreateTrivial: "hxc_array_ref_create_trivial";
			case CBRNArrayInitInPlace: "hxc_array_ref_init_in_place";
			case CBRNArrayCopy: "hxc_array_ref_copy";
			case CBRNArrayCopyInPlace: "hxc_array_ref_copy_in_place";
			case CBRNArrayDisposeInPlace: "hxc_array_ref_dispose_in_place";
			case CBRNArrayElementOpsType: "hxc_array_element_ops";
			case CBRNArrayGetCopy: "hxc_array_ref_get_copy";
			case CBRNArrayLength: "hxc_array_ref_length";
			case CBRNArrayPopMove: "hxc_array_ref_pop_move";
			case CBRNArrayShiftMove: "hxc_array_ref_shift_move";
			case CBRNArraySpliceOneDiscard: "hxc_array_ref_splice_one_discard";
			case CBRNArraySpliceOneCopy: "hxc_array_ref_splice_one_copy";
			case CBRNArraySpliceDiscard: "hxc_array_ref_splice_discard";
			case CBRNArraySpliceCopy: "hxc_array_ref_splice_copy";
			case CBRNArrayInsertCopy: "hxc_array_ref_insert_copy";
			case CBRNArrayPushCopy: "hxc_array_ref_push_copy";
			case CBRNArraySetCopy: "hxc_array_ref_set_copy";
			case CBRNArraySort: "hxc_array_ref_sort";
			case CBRNArrayRetain: "hxc_array_ref_retain";
			case CBRNArrayRelease: "hxc_array_ref_release";
			case CBRNArrayReleaseSlot: "hxc_array_ref_release_slot";
			case CBRNArrayStoragePushCopy: "hxc_array_push_copy";
			case CBRNArrayStorageResize: "hxc_array_resize";
			case CBRNArrayResizeDefault: "hxc_array_ref_resize_default";
			case CBRNArrayValueMember: "value";
			case CBRNStringMapCreate: "hxc_string_map_ref_create";
			case CBRNStringMapCreateWithOps: "hxc_string_map_ref_create_with_ops";
			case CBRNStringMapValueOpsType: "hxc_string_map_value_ops";
			case CBRNStringMapRetain: "hxc_string_map_ref_retain";
			case CBRNStringMapRelease: "hxc_string_map_ref_release";
			case CBRNStringMapReleaseSlot: "hxc_string_map_ref_release_slot";
			case CBRNStringMapCopy: "hxc_string_map_ref_copy";
			case CBRNStringMapSetCopy: "hxc_string_map_ref_set_copy";
			case CBRNStringMapExists: "hxc_string_map_ref_exists";
			case CBRNStringMapGetCopy: "hxc_string_map_ref_get_copy";
			case CBRNStringMapRemove: "hxc_string_map_ref_remove";
			case CBRNStringMapClear: "hxc_string_map_ref_clear";
			case CBRNStringMapValueIterator: "hxc_string_map_ref_value_iterator";
			case CBRNStringMapKeyIterator: "hxc_string_map_ref_key_iterator";
			case CBRNStringMapPairIterator: "hxc_string_map_ref_pair_iterator";
			case CBRNStringMapToString: "hxc_string_map_ref_to_string";
			case CBRNIteratorCreateArrayValues: "hxc_iterator_ref_create_array_values";
			case CBRNIteratorCreateArrayPairs: "hxc_iterator_ref_create_array_pairs";
			case CBRNIteratorRetain: "hxc_iterator_ref_retain";
			case CBRNIteratorRelease: "hxc_iterator_ref_release";
			case CBRNIteratorReleaseSlot: "hxc_iterator_ref_release_slot";
			case CBRNIteratorHasNext: "hxc_iterator_ref_has_next";
			case CBRNIteratorNextMove: "hxc_iterator_ref_next_move";
			case CBRNIntMapCreate: "hxc_int_bool_map_ref_create";
			case CBRNIntMapRetain: "hxc_int_bool_map_ref_retain";
			case CBRNIntMapRelease: "hxc_int_bool_map_ref_release";
			case CBRNIntMapReleaseSlot: "hxc_int_bool_map_ref_release_slot";
			case CBRNIntMapCopy: "hxc_int_bool_map_ref_copy";
			case CBRNIntMapSet: "hxc_int_bool_map_ref_set";
			case CBRNIntMapExists: "hxc_int_bool_map_ref_exists";
			case CBRNIntMapGet: "hxc_int_bool_map_ref_get";
			case CBRNIntMapRemove: "hxc_int_bool_map_ref_remove";
			case CBRNIntMapClear: "hxc_int_bool_map_ref_clear";
			case CBRNIntMapValueIterator: "hxc_int_bool_map_ref_value_iterator";
			case CBRNIntMapKeyIterator: "hxc_int_bool_map_ref_key_iterator";
			case CBRNIntMapPairIterator: "hxc_int_bool_map_ref_pair_iterator";
			case CBRNIntMapToString: "hxc_int_bool_map_ref_to_string";
			case CBRNTypedMapTypeDescriptor: "hxc_typed_map_type_descriptor";
			case CBRNTypedMapIdentityHash: "hxc_typed_map_identity_hash";
			case CBRNTypedMapHashMix: "hxc_typed_map_hash_mix";
			case CBRNTypedMapInitCollectorOwned: "hxc_typed_map_init_collector_owned";
			case CBRNTypedMapCopyInPlace: "hxc_typed_map_copy_in_place";
			case CBRNTypedMapSetCopy: "hxc_typed_map_ref_set_copy";
			case CBRNTypedMapExists: "hxc_typed_map_ref_exists";
			case CBRNTypedMapGetCopy: "hxc_typed_map_ref_get_copy";
			case CBRNTypedMapRemove: "hxc_typed_map_ref_remove";
			case CBRNTypedMapClear: "hxc_typed_map_ref_clear";
			case CBRNTypedMapValueIterator: "hxc_typed_map_ref_value_iterator";
			case CBRNTypedMapKeyIterator: "hxc_typed_map_ref_key_iterator";
			case CBRNTypedMapPairIterator: "hxc_typed_map_ref_pair_iterator";
			case CBRNTypedMapKeyOpsType: "hxc_typed_map_key_ops";
			case CBRNTypedMapValueOpsType: "hxc_typed_map_value_ops";
			case CBRNIteratorElementOpsType: "hxc_iterator_element_ops";
			case CBRNBytesCreateZeroed: "hxc_bytes_ref_create_zeroed";
			case CBRNBytesCreateUtf8Copy: "hxc_bytes_ref_create_utf8_copy";
			case CBRNBytesLength: "hxc_bytes_ref_length";
			case CBRNBytesGet: "hxc_bytes_ref_get";
			case CBRNBytesSet: "hxc_bytes_ref_set";
			case CBRNBytesSub: "hxc_bytes_ref_sub";
			case CBRNBytesBlit: "hxc_bytes_ref_blit";
			case CBRNBytesFill: "hxc_bytes_ref_fill";
			case CBRNBytesCompare: "hxc_bytes_ref_compare";
			case CBRNBytesBorrowMutableCString: "hxc_bytes_ref_borrow_mutable_cstring";
			case CBRNBytesGetStringUtf8: "hxc_bytes_ref_get_string_utf8";
			case CBRNBytesRetain: "hxc_bytes_ref_retain";
			case CBRNBytesRelease: "hxc_bytes_ref_release";
			case CBRNBytesReleaseSlot: "hxc_bytes_ref_release_slot";
			case CBRNDynamicValueType: "hxc_value";
			case CBRNDynamicTypeDescriptorType: "hxc_dynamic_type";
			case CBRNDynamicTypeAbiVersion: "HXC_DYNAMIC_TYPE_ABI_VERSION";
			case CBRNDynamicCategoryNull: "HXC_DYNAMIC_CATEGORY_NULL";
			case CBRNDynamicCategoryBool: "HXC_DYNAMIC_CATEGORY_BOOL";
			case CBRNDynamicCategoryInt: "HXC_DYNAMIC_CATEGORY_INT";
			case CBRNDynamicCategoryFloat: "HXC_DYNAMIC_CATEGORY_FLOAT";
			case CBRNDynamicCategoryString: "HXC_DYNAMIC_CATEGORY_STRING";
			case CBRNDynamicCategoryArray: "HXC_DYNAMIC_CATEGORY_ARRAY";
			case CBRNDynamicCategoryObject: "HXC_DYNAMIC_CATEGORY_OBJECT";
			case CBRNDynamicCategoryEnum: "HXC_DYNAMIC_CATEGORY_ENUM";
			case CBRNDynamicCategoryFunction: "HXC_DYNAMIC_CATEGORY_FUNCTION";
			case CBRNDynamicCategoryTypeValue: "HXC_DYNAMIC_CATEGORY_TYPE_VALUE";
			case CBRNDynamicStorageInlineNull: "HXC_DYNAMIC_STORAGE_INLINE_NULL";
			case CBRNDynamicStorageInlineBool: "HXC_DYNAMIC_STORAGE_INLINE_BOOL";
			case CBRNDynamicStorageInlineInt32: "HXC_DYNAMIC_STORAGE_INLINE_INT32";
			case CBRNDynamicStorageInlineFloat64: "HXC_DYNAMIC_STORAGE_INLINE_FLOAT64";
			case CBRNDynamicStorageManagedReference: "HXC_DYNAMIC_STORAGE_MANAGED_REFERENCE";
			case CBRNDynamicStorageManagedWrapper: "HXC_DYNAMIC_STORAGE_MANAGED_WRAPPER";
			case CBRNDynamicStorageStaticToken: "HXC_DYNAMIC_STORAGE_STATIC_TOKEN";
			case CBRNDynamicInvalidInitializer: "HXC_VALUE_INVALID_INITIALIZER";
			case CBRNDynamicInitNull: "hxc_value_init_null";
			case CBRNDynamicInitBool: "hxc_value_init_bool";
			case CBRNDynamicInitInt32: "hxc_value_init_int32";
			case CBRNDynamicInitFloat64: "hxc_value_init_float64";
			case CBRNDynamicInitManagedReference: "hxc_value_init_managed_reference";
			case CBRNDynamicInitManagedWrapper: "hxc_value_init_managed_wrapper";
			case CBRNDynamicInitStaticToken: "hxc_value_init_static_token";
			case CBRNDynamicReadBool: "hxc_value_read_bool";
			case CBRNDynamicReadInt32: "hxc_value_read_int32";
			case CBRNDynamicReadFloat64: "hxc_value_read_float64";
			case CBRNDynamicReadManagedReference: "hxc_value_read_managed_reference";
			case CBRNDynamicReadManagedWrapper: "hxc_value_read_managed_wrapper";
			case CBRNDynamicReadStaticToken: "hxc_value_read_static_token";
			case CBRNDynamicManagedPayload: "hxc_value_managed_payload";
			case CBRNDynamicTypeField: "type";
			case CBRNDynamicActiveStorageField: "active_storage";
			case CBRNDynamicPayloadField: "payload";
			case CBRNDynamicPayloadObjectField: "object";
			case CBRNDynamicPayloadBoolField: "boolean";
			case CBRNDynamicPayloadInt32Field: "int32_value";
			case CBRNDynamicPayloadFloat64Field: "float64_value";
			case CBRNDynamicDescriptorAbiVersionField: "abi_version";
			case CBRNDynamicDescriptorTypeIdField: "type_id";
			case CBRNDynamicDescriptorCategoryField: "category";
			case CBRNDynamicDescriptorStorageField: "storage";
		});
	}
}
