package raygui.raw;

/**
 * ABI-faithful raygui 5.0 editor-shell function namespace.
 *
 * Generated by scripts/raygui/core_binding.py from commit 020a61bebcbe288b4414de3416e219ef40af847a.
 * Edit the selection/generator and run its registered check; do not
 * hand-edit this raw declaration.
 */
#if raylib_system_pkg_config
@:c.pkgConfig("raylib")
@:c.link("raygui")
#elseif raylib_platform_linux
@:c.link("raygui")
@:c.link("raylib")
@:c.link("m")
	#if raylib_configuration_desktop
	@:c.link("pthread") @:c.link("GL") @:c.link("X11") @:c.link("dl") @:c.link("rt")
	#end
#elseif raylib_platform_macos
@:c.link("raygui")
@:c.link("raylib")
	#if raylib_configuration_desktop
	@:c.framework("OpenGL") @:c.framework("Cocoa") @:c.framework("IOKit") @:c.framework("CoreFoundation")
	#end
#elseif raylib_platform_windows
@:c.link("raygui")
@:c.link("raylib")
@:c.link("winmm")
	#if raylib_configuration_desktop
	@:c.link("opengl32") @:c.link("gdi32") @:c.link("shell32") @:c.link("user32")
	#end
#end
@:c.include("raygui.h", c.IncludeKind.System)
extern class Raygui {
	public static function GuiButton(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiDisable():Void;

	public static function GuiDummyRec(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiEnable():Void;

	public static function GuiGetState():c.Int32;

	public static function GuiGetStyle(control:c.Int32, property:c.Int32):c.Int32;

	public static function GuiGetTextWidth(text:c.CString):c.Int32;

	public static function GuiGroupBox(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiIsLocked():Bool;

	public static function GuiLabel(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiLabelButton(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiLine(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiLoadStyleDefault():Void;

	public static function GuiLock():Void;

	public static function GuiPanel(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiSetAlpha(alpha:c.Float32):Void;

	public static function GuiSetState(state:c.Int32):Void;

	public static function GuiSetStyle(control:c.Int32, property:c.Int32, value:c.Int32):Void;

	public static function GuiStatusBar(bounds:raylib.raw.Rectangle, text:c.CString):c.Int32;

	public static function GuiUnlock():Void;

	public static function GuiWindowBox(bounds:raylib.raw.Rectangle, title:c.CString):c.Int32;
}
