#include "hxc/program.h"

int32_t hxc_field_AStaticInitDependent_first;

int32_t hxc_field_AStaticInitDependent_second;

int32_t hxc_field_AStaticInitDependent_value;

int32_t hxc_field_MStaticInitTrace_classOrder;

int32_t hxc_field_MStaticInitTrace_phaseValue;

int32_t hxc_field_MStaticInitTrace_trace;

int32_t hxc_field_zZStaticInitPrerequisite_value;

int32_t hxc_method_MStaticInitTrace_mark(int32_t hxc_local_MStaticInitTrace_mark_digit_n0)
{
  int32_t hxc_temp_MStaticInitTrace_mark_globalzx2Dloadzx2Dresult_n0 = hxc_field_MStaticInitTrace_trace;
  hxc_field_MStaticInitTrace_trace = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_temp_MStaticInitTrace_mark_globalzx2Dloadzx2Dresult_n0, 10), hxc_local_MStaticInitTrace_mark_digit_n0);
  int32_t hxc_temp_MStaticInitTrace_mark_globalzx2Dloadzx2Dresult_n1 = hxc_field_MStaticInitTrace_trace;
  return hxc_temp_MStaticInitTrace_mark_globalzx2Dloadzx2Dresult_n1;
}

int32_t hxc_method_MStaticInitTrace_seed(void)
{
  return 1;
}

void hxc_method_StaticInitializzationFixture_main(void)
{
  hxc_method_StaticInitializzationFixture_outcome();
  return;
}

int32_t hxc_method_StaticInitializzationFixture_outcome(void)
{
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n0 = hxc_field_MStaticInitTrace_classOrder;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n1 = hxc_field_MStaticInitTrace_phaseValue;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n2 = hxc_field_MStaticInitTrace_trace;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n3 = hxc_field_zZStaticInitPrerequisite_value;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n4 = hxc_field_AStaticInitDependent_first;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n5 = hxc_field_AStaticInitDependent_second;
  int32_t hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n6 = hxc_field_AStaticInitDependent_value;
  return hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n0, hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n1), hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n2), hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n3), hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n4), hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n5), hxc_temp_StaticInitializzationFixture_outcome_globalzx2Dloadzx2Dresult_n6);
}

void hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_classzx2Dinit_n0(void)
{
  int32_t hxc_temp_AStaticInitDependent_classzx2Dinit_globalzx2Dloadzx2Dresult_n0 = hxc_field_MStaticInitTrace_classOrder;
  hxc_field_MStaticInitTrace_classOrder = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_temp_AStaticInitDependent_classzx2Dinit_globalzx2Dloadzx2Dresult_n0, 10), 3);
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dfirst_n1(void)
{
  int32_t hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dfirst_globalzx2Dloadzx2Dresult_n0 = hxc_field_zZStaticInitPrerequisite_value;
  hxc_field_AStaticInitDependent_first = hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dfirst_globalzx2Dloadzx2Dresult_n0;
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dsecond_n2(void)
{
  int32_t hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dsecond_globalzx2Dloadzx2Dresult_n0 = hxc_field_AStaticInitDependent_first;
  hxc_field_AStaticInitDependent_second = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dsecond_globalzx2Dloadzx2Dresult_n0, 5);
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_n3(void)
{
  int32_t hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_callzx2Dresult_n0 = hxc_method_MStaticInitTrace_mark(3);
  int32_t hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_globalzx2Dloadzx2Dresult_n1 = hxc_field_zZStaticInitPrerequisite_value;
  int32_t hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_globalzx2Dloadzx2Dresult_n2 = hxc_field_AStaticInitDependent_second;
  hxc_field_AStaticInitDependent_value = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_callzx2Dresult_n0, hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_globalzx2Dloadzx2Dresult_n1), hxc_temp_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_globalzx2Dloadzx2Dresult_n2);
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_classzx2Dinit_n0(void)
{
  hxc_field_MStaticInitTrace_phaseValue = 3;
  hxc_field_MStaticInitTrace_classOrder = 1;
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2DclassOrder_n1(void)
{
  int32_t hxc_temp_MStaticInitTrace_staticzx2Dfieldzx2DclassOrder_globalzx2Dloadzx2Dresult_n0 = hxc_field_MStaticInitTrace_classOrder;
  hxc_field_MStaticInitTrace_classOrder = hxc_temp_MStaticInitTrace_staticzx2Dfieldzx2DclassOrder_globalzx2Dloadzx2Dresult_n0;
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2DphaseValue_n2(void)
{
  hxc_field_MStaticInitTrace_phaseValue = 7;
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2Dtrace_n3(void)
{
  int32_t hxc_temp_MStaticInitTrace_staticzx2Dfieldzx2Dtrace_callzx2Dresult_n0 = hxc_method_MStaticInitTrace_seed();
  hxc_field_MStaticInitTrace_trace = hxc_temp_MStaticInitTrace_staticzx2Dfieldzx2Dtrace_callzx2Dresult_n0;
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_zZStaticInitPrerequisite_classzx2Dinit_n0(void)
{
  int32_t hxc_temp_zZStaticInitPrerequisite_classzx2Dinit_globalzx2Dloadzx2Dresult_n0 = hxc_field_MStaticInitTrace_classOrder;
  hxc_field_MStaticInitTrace_classOrder = hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Eaddzx2Ewrapping(hxc_spec_compiler_primitivezx2Dhelper_of_hxczx2Ei32zx2Emultiplyzx2Ewrapping(hxc_temp_zZStaticInitPrerequisite_classzx2Dinit_globalzx2Dloadzx2Dresult_n0, 10), 2);
  return;
}

void hxc_init_compiler_staticzx2Dinitializzation_zZStaticInitPrerequisite_staticzx2Dfieldzx2Dvalue_n1(void)
{
  int32_t hxc_temp_zZStaticInitPrerequisite_staticzx2Dfieldzx2Dvalue_callzx2Dresult_n0 = hxc_method_MStaticInitTrace_mark(2);
  hxc_field_zZStaticInitPrerequisite_value = hxc_temp_zZStaticInitPrerequisite_staticzx2Dfieldzx2Dvalue_callzx2Dresult_n0;
  return;
}

static void hxc_init_compiler_staticzx2Dinitializzation_hostedzx2Dexecutable_functionzx2EStaticInitializzationFixturezx2Emain(void)
{
  hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_classzx2Dinit_n0();
  hxc_init_compiler_staticzx2Dinitializzation_zZStaticInitPrerequisite_classzx2Dinit_n0();
  hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_classzx2Dinit_n0();
  hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2DclassOrder_n1();
  hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2DphaseValue_n2();
  hxc_init_compiler_staticzx2Dinitializzation_MStaticInitTrace_staticzx2Dfieldzx2Dtrace_n3();
  hxc_init_compiler_staticzx2Dinitializzation_zZStaticInitPrerequisite_staticzx2Dfieldzx2Dvalue_n1();
  hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dfirst_n1();
  hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dsecond_n2();
  hxc_init_compiler_staticzx2Dinitializzation_AStaticInitDependent_staticzx2Dfieldzx2Dvalue_n3();
}

int main(void)
{
  hxc_init_compiler_staticzx2Dinitializzation_hostedzx2Dexecutable_functionzx2EStaticInitializzationFixturezx2Emain();
  hxc_method_StaticInitializzationFixture_main();
  return 0;
}
