import reflaxe.c.ast.CAST;
import reflaxe.c.ast.CASTPrinter;
import reflaxe.c.emit.GeneratedFile;
import reflaxe.c.emit.GeneratedFile.GeneratedFileKind;
import sys.io.File;

/**
 * Builds bounded, repeatable C AST programs from checked-in seeds and text data.
 *
 * Each seed produces an independent strict-C11 translation unit. The same files
 * are emitted twice through Reflaxe ownership so the host runner can compare all
 * generated bytes without starting the Haxe compiler a second time.
 */
class CASTFuzzCompiler {
	static final MAX_SEEDS = 16;
	static final MAX_CASES = 64;
	static final MAX_DICTIONARY_ENTRIES = 64;
	static final MAX_TEXT_CODE_POINTS = 128;

	/** Emits two copies of the requested prefix-stable corpus for comparison. */
	public static function run(outputRoot:String, seedsPath:String, dictionaryPath:String, cases:Int):Void {
		if (cases < 1 || cases > MAX_CASES)
			throw 'C AST fuzz case count must be between 1 and $MAX_CASES';
		final seeds = readSeeds(seedsPath);
		final dictionary = readDictionary(dictionaryPath);
		final printer = new CASTPrinter();
		final files:Array<GeneratedFile> = [];
		for (seed in seeds) {
			final source = printer.printTranslationUnit(buildUnit(seed.value, cases, dictionary));
			files.push(new GeneratedFile('seed-${seed.name}.c', source, GeneratedFileKind.Source));
		}
		ASTFixtureCompiler.writeFiles(outputRoot + "/first", files);
		ASTFixtureCompiler.writeFiles(outputRoot + "/second", files);
		Sys.println('c-ast-fuzz-macro: OK: ${seeds.length} seeds x $cases cases');
	}

	/** Builds one self-checking unit whose first N cases never depend on later cases. */
	static function buildUnit(seed:Int, cases:Int, dictionary:Array<String>):CTranslationUnit {
		final unit = new CTranslationUnit();
		unit.includes.push({path: "stdint.h", kind: System});
		unit.includes.push({path: "stdio.h", kind: System});
		unit.declarations.push(DComment(dictionary[positiveMod(seed, dictionary.length)]));

		var expected = 0;
		for (index in 0...cases) {
			final first = valueFor(seed, index, 17);
			final second = valueFor(seed, index, 53);
			final variant = positiveMod(seed + index, 4);
			final result = variant % 2 == 0 ? first ^ second : first + second;
			expected = expected ^ result;
			final text = dictionary[positiveMod(seed + index * 7, dictionary.length)];
			final resultExpression = variant % 2 == 0 ? EBinary(BitXor, EIndex(identifier('values_$index'), integer("0")),
				EIndex(identifier('values_$index'),
					integer("1"))) : EBinary(Add, EIndex(identifier('values_$index'), integer("0")), EIndex(identifier('values_$index'), integer("1")));
			unit.declarations.push(DStaticAssert(EBinary(NotEqual, integer(Std.string(first)), integer(Std.string(second))), "fuzz values differ"));
			unit.declarations.push(DFunction({
				storage: [SStatic],
				functionSpecifiers: [],
				returnType: u32(),
				declarator: DFunction(name('hxc_fuzz_case_$index'), FPPrototype([], false)),
				body: SBlock([
					SComment(text),
					SLineDirective({
						line: index + 1,
						file: variant == 0 ? null : text
					}),
					SDecl({
						storage: [],
						alignments: [],
						type: type(TChar(null), [QConst]),
						declarator: DPointer(name('text_$index'), []),
						initializer: IExpr(EString(text)),
						attributes: []
					}),
					SDecl({
						storage: [],
						alignments: [],
						type: u32(),
						declarator: DArray(name('values_$index'), ABFixed(integer("2")), []),
						initializer: IList([
							{designators: [], value: IExpr(integer(Std.string(first)))},
							{designators: [], value: IExpr(integer(Std.string(second)))}
						]),
						attributes: []
					}),
					SDecl(shapeDeclaration(seed, index)),
					SExpr(ECast(type(TVoid), DName(null), identifier('text_$index'))),
					SExpr(ECast(type(TVoid), DName(null), identifier('shape_$index'))),
					SReturn(resultExpression)
				]),
				attributes: []
			}));
		}

		final statements:Array<CStmt> = [
			SDecl({
				storage: [],
				alignments: [],
				type: u32(),
				declarator: name("observed"),
				initializer: IExpr(integer("0")),
				attributes: []
			})
		];
		for (index in 0...cases)
			statements.push(SExpr(EBinary(BitXorAssign, identifier("observed"), ECall(identifier('hxc_fuzz_case_$index'), []))));
		statements.push(SIf(EBinary(NotEqual, identifier("observed"), integer(Std.string(expected))), SReturn(integer("1")), null));
		statements.push(SExpr(ECall(identifier("puts"), [EString("c-ast-fuzz: OK")])));
		statements.push(SReturn(integer("0")));
		unit.declarations.push(DFunction({
			storage: [],
			functionSpecifiers: [],
			returnType: nativeInt(),
			declarator: DFunction(name("main"), FPPrototype([], false)),
			body: SBlock(statements),
			attributes: []
		}));
		return unit;
	}

	/** Selects one valid declarator grammar shape without using target-code text. */
	static function shapeDeclaration(seed:Int, index:Int):CVariableDecl {
		final values = identifier('values_$index');
		final shapeName = name('shape_$index');
		return switch (positiveMod(seed + index, 4)) {
			case 0:
				variable(u32(), DPointer(shapeName, []), IExpr(values));
			case 1:
				variable(u32(), DArray(DGroup(DPointer(shapeName, [])), ABFixed(integer("2")), []), IExpr(EUnary(AddressOf, values)));
			case 2:
				variable(u32(), DPointer(DArray(shapeName, ABFixed(integer("1")), []), []), IList([{designators: [], value: IExpr(values)}]));
			case _:
				variable(type(TInt(32, false), [QConst]), DPointer(shapeName, [QConst]), IExpr(values));
		};
	}

	/** Creates one local declaration with the shared no-storage/no-attribute policy. */
	static function variable(type:CType, declarator:CDeclarator, initializer:CInitializer):CVariableDecl
		return {
			storage: [],
			alignments: [],
			type: type,
			declarator: declarator,
			initializer: initializer,
			attributes: []
		};

	/** Reads the small typed seed boundary and rejects names unsafe for output paths. */
	static function readSeeds(path:String):Array<{name:String, value:Int}> {
		final seeds:Array<{name:String, value:Int}> = [];
		for (line in File.getContent(path).split("\n")) {
			if (line.length == 0 || StringTools.startsWith(line, "#"))
				continue;
			final fields = line.split("\t");
			if (fields.length != 2 || !~/^[a-z0-9][a-z0-9-]*$/.match(fields[0]))
				throw 'Invalid C AST fuzz seed row: $line';
			final value = Std.parseInt(fields[1]);
			if (value == null || value < 0)
				throw 'Invalid C AST fuzz seed value: ${fields[1]}';
			seeds.push({name: fields[0], value: value});
		}
		if (seeds.length < 1 || seeds.length > MAX_SEEDS)
			throw 'C AST fuzz seed count must be between 1 and $MAX_SEEDS';
		return seeds;
	}

	/** Decodes reviewed Unicode code points without allowing untyped data into the AST. */
	static function readDictionary(path:String):Array<String> {
		final entries:Array<String> = [];
		for (line in File.getContent(path).split("\n")) {
			if (line.length == 0 || StringTools.startsWith(line, "#"))
				continue;
			final fields = line.split("\t");
			if (fields.length != 2)
				throw 'Invalid C AST fuzz dictionary row: $line';
			final codePoints = fields[1].split(",");
			if (codePoints.length > MAX_TEXT_CODE_POINTS)
				throw 'C AST fuzz dictionary entry is too long: ${fields[0]}';
			final buffer = new StringBuf();
			for (encoded in codePoints) {
				final value = Std.parseInt("0x" + encoded);
				if (value == null || value < 0 || value > 0x10ffff || (value >= 0xd800 && value <= 0xdfff))
					throw 'Invalid Unicode code point $encoded in ${fields[0]}';
				buffer.addChar(value);
			}
			entries.push(buffer.toString());
		}
		if (entries.length < 1 || entries.length > MAX_DICTIONARY_ENTRIES)
			throw 'C AST fuzz dictionary count must be between 1 and $MAX_DICTIONARY_ENTRIES';
		return entries;
	}

	static function valueFor(seed:Int, index:Int, salt:Int):Int
		return positiveMod(seed + index * 7919 + salt * 104729, 65521);

	static function positiveMod(value:Int, modulus:Int):Int {
		final result = value % modulus;
		return result < 0 ? result + modulus : result;
	}

	static function id(value:String):CIdentifier
		return new CIdentifier(value);

	static function identifier(value:String):CExpr
		return EIdentifier(id(value));

	static function type(spec:CTypeSpec, ?qualifiers:Array<CQualifier>):CType
		return new CType(spec, qualifiers);

	static function u32():CType
		return type(TInt(32, false));

	static function nativeInt():CType
		return type(TNativeInt(IRInt, true));

	static function integer(value:String):CExpr
		return EInt(CIntegerLiteral.decimal(value, ISUnsigned));

	static function name(value:String):CDeclarator
		return DName(id(value));
}
