#include <cstdio>

#include "raylib.h"

/*
 * Independent C++17 consumer for the selected gamepad ABI.
 *
 * This source is handwritten so it checks the pinned public header and linked
 * Raylib library without asking haxe.c to verify declarations generated by
 * haxe.c. Taking typed function addresses proves C++ sees the same parameter
 * and return shapes; no window or physical controller is required.
 */
int main() {
  bool (*available)(int) = &IsGamepadAvailable;
  bool (*pressed)(int, int) = &IsGamepadButtonPressed;
  bool (*down)(int, int) = &IsGamepadButtonDown;
  float (*axis)(int, int) = &GetGamepadAxisMovement;
  if ((available == nullptr) || (pressed == nullptr) || (down == nullptr) ||
      (axis == nullptr)) {
    return 1;
  }
  std::puts("raylib-cpp-consumer: OK");
  return 0;
}
